### ISSUE TITLE
-1 precision and F1 for ConLL data

### ISSUE THREAD

**Issue by vidhishanair** [jiesutd/NCRFpp#100]
Hi,
I'm unable to reproduce results for ConLL2003 NER data.
I even tried converting my data from BIO-BIOES using your script. Please help me understand what I've done wrong.

Below is the log with BIOES train: 

Seed num: 42
MODEL: train
Load pretrained word embedding, norm: False, dir: ../data/glove.6B/glove.6B.100d.txt
Embedding:
     pretrain word:400000, prefect match:3, case_match:0, oov:1, oov%:0.2
Training model...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DATA SUMMARY START:
 I/O:
     Start   Sequence   Laebling   task...
     Tag          scheme: BMES
     Split         token:  |||
     MAX SENTENCE LENGTH: 250
     MAX   WORD   LENGTH: -1
     Number   normalized: True
     Word  alphabet size: 5
     Char  alphabet size: 3
     Label alphabet size: 18
     Word embedding  dir: ../data/glove.6B/glove.6B.100d.txt
     Char embedding  dir: None
     Word embedding size: 100
     Char embedding size: 30
     Norm   word     emb: False
     Norm   char     emb: False
     Train  file directory: ../data/modified_data/eng.train.bioes
     Dev    file directory: ../data/modified_data/eng.testa.bioes
     Test   file directory: ../data/modified_data/eng.testb.bioes
     Raw    file directory: None
     Dset   file directory: None
     Model  file directory: ../data/charcnnwordlstmcrftestbioes
     Loadmodel   directory: None
     Decode file directory: None
     Train instance number: 14986
     Dev   instance number: 3465
     Test  instance number: 3683
     Raw   instance number: 0
     FEATURE num: 0
 ++++++++++++++++++++++++++++++++++++++++
 Model Network:
     Model        use_crf: True
     Model word extractor: LSTM
     Model       use_char: True
     Model char extractor: CNN
     Model char_hidden_dim: 50
 ++++++++++++++++++++++++++++++++++++++++
 Training:
     Optimizer: SGD
     Iteration: 100
     BatchSize: 10
     Average  batch   loss: True
 ++++++++++++++++++++++++++++++++++++++++
 Hyperparameters:
     Hyper              lr: 0.015
     Hyper        lr_decay: 0.05
     Hyper         HP_clip: None
     Hyper        momentum: 0.0
     Hyper              l2: 1e-08
     Hyper      hidden_dim: 200
     Hyper         dropout: 0.5
     Hyper      lstm_layer: 1
     Hyper          bilstm: True
     Hyper             GPU: True
DATA SUMMARY END.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
build sequence labeling network...
use_char:  True
char feature extractor:  CNN
word feature extractor:  LSTM
use crf:  True
build word sequence feature extractor: LSTM...
build word representation...
build char sequence feature extractor: CNN ...
build CRF...
Epoch: 0/100
 Learning rate is set as: 0.015
Shuffle: first input word list: [2, 2, 2, 2, 2, 2, 2]
     Instance: 500; Time: 5.65s; loss: 688.5860; acc: 5410/6734=0.8034
     Instance: 1000; Time: 5.89s; loss: 572.2787; acc: 11774/14229=0.8275
     Instance: 1500; Time: 5.42s; loss: 527.8886; acc: 18033/21551=0.8368
     Instance: 2000; Time: 5.59s; loss: 551.2242; acc: 23748/28433=0.8352
     Instance: 2500; Time: 5.40s; loss: 512.4623; acc: 29489/35255=0.8364
     Instance: 3000; Time: 5.25s; loss: 481.4681; acc: 35058/41839=0.8379
     Instance: 3500; Time: 5.73s; loss: 554.1080; acc: 41089/49084=0.8371
     Instance: 4000; Time: 5.31s; loss: 514.6246; acc: 46476/55640=0.8353
     Instance: 4500; Time: 5.15s; loss: 521.3245; acc: 51936/62275=0.8340
     Instance: 5000; Time: 5.42s; loss: 526.3831; acc: 57730/69309=0.8329
     Instance: 5500; Time: 5.54s; loss: 520.3846; acc: 63471/76261=0.8323
     Instance: 6000; Time: 5.72s; loss: 480.5155; acc: 69338/83262=0.8328
     Instance: 6500; Time: 5.51s; loss: 495.4523; acc: 75078/90162=0.8327
     Instance: 7000; Time: 5.60s; loss: 488.3297; acc: 81048/97261=0.8333
     Instance: 7500; Time: 5.44s; loss: 469.5476; acc: 86391/103745=0.8327
     Instance: 8000; Time: 5.51s; loss: 477.6908; acc: 92115/110597=0.8329
     Instance: 8500; Time: 5.34s; loss: 466.7520; acc: 97842/117457=0.8330
     Instance: 9000; Time: 5.42s; loss: 460.8916; acc: 103260/124017=0.8326
     Instance: 9500; Time: 5.39s; loss: 421.7527; acc: 108522/130318=0.8327
     Instance: 10000; Time: 5.57s; loss: 444.7986; acc: 114220/137079=0.8332
     Instance: 10500; Time: 5.37s; loss: 438.1787; acc: 119643/143589=0.8332
     Instance: 11000; Time: 5.47s; loss: 443.6167; acc: 125421/150452=0.8336
     Instance: 11500; Time: 5.66s; loss: 465.6778; acc: 131328/157521=0.8337
     Instance: 12000; Time: 5.70s; loss: 441.7232; acc: 137153/164439=0.8341
     Instance: 12500; Time: 5.23s; loss: 456.5177; acc: 142728/171152=0.8339
     Instance: 13000; Time: 5.33s; loss: 443.0195; acc: 148391/177974=0.8338
     Instance: 13500; Time: 5.07s; loss: 436.1295; acc: 153527/184243=0.8333
     Instance: 14000; Time: 5.61s; loss: 488.2037; acc: 159389/191383=0.8328
     Instance: 14500; Time: 5.53s; loss: 435.6175; acc: 164958/198074=0.8328
     Instance: 14986; Time: 5.28s; loss: 398.8262; acc: 170415/204566=0.8331
Epoch: 0 training finished. Time: 164.08s, speed: 91.33st/s,  total loss: 14623.973976135254
totalloss: 14623.973976135254
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.14s, speed: 565.80st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Exceed previous best f score: -10
Save current best model in file: ../data/charcnnwordlstmcrftestbioes.0.model
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.83s, speed: 635.29st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000
Epoch: 1/100
 Learning rate is set as: 0.014285714285714285
Shuffle: first input word list: [2, 2]
     Instance: 500; Time: 5.08s; loss: 431.2016; acc: 5391/6521=0.8267
     Instance: 1000; Time: 5.47s; loss: 439.1820; acc: 10921/13222=0.8260
     Instance: 1500; Time: 5.50s; loss: 423.6805; acc: 16460/19866=0.8286
     Instance: 2000; Time: 5.46s; loss: 425.2254; acc: 22446/26950=0.8329
     Instance: 2500; Time: 5.90s; loss: 435.6300; acc: 28570/34178=0.8359
     Instance: 3000; Time: 5.35s; loss: 444.1788; acc: 34283/41039=0.8354
     Instance: 3500; Time: 5.36s; loss: 430.6110; acc: 39931/47798=0.8354
     Instance: 4000; Time: 5.26s; loss: 431.6148; acc: 45356/54376=0.8341
     Instance: 4500; Time: 5.55s; loss: 450.8224; acc: 51271/61468=0.8341
     Instance: 5000; Time: 5.46s; loss: 429.3036; acc: 57317/68630=0.8352
     Instance: 5500; Time: 5.60s; loss: 449.7797; acc: 63241/75743=0.8349
     Instance: 6000; Time: 5.27s; loss: 433.6448; acc: 68693/82380=0.8339
     Instance: 6500; Time: 5.71s; loss: 456.3143; acc: 74874/89753=0.8342
     Instance: 7000; Time: 5.25s; loss: 436.8700; acc: 80510/96573=0.8337
     Instance: 7500; Time: 5.63s; loss: 430.2619; acc: 86279/103481=0.8338
     Instance: 8000; Time: 5.72s; loss: 412.8583; acc: 92142/110434=0.8344
     Instance: 8500; Time: 5.54s; loss: 398.9669; acc: 97755/117099=0.8348
     Instance: 9000; Time: 5.58s; loss: 401.6885; acc: 103315/123734=0.8350
     Instance: 9500; Time: 5.71s; loss: 401.0224; acc: 109076/130581=0.8353
     Instance: 10000; Time: 5.61s; loss: 436.5150; acc: 114616/137309=0.8347
     Instance: 10500; Time: 5.47s; loss: 422.0465; acc: 120169/144025=0.8344
     Instance: 11000; Time: 5.45s; loss: 392.8255; acc: 125509/150463=0.8342
     Instance: 11500; Time: 5.66s; loss: 430.9805; acc: 131225/157359=0.8339
     Instance: 12000; Time: 5.81s; loss: 429.5823; acc: 137266/164574=0.8341
     Instance: 12500; Time: 5.47s; loss: 409.2201; acc: 143011/171457=0.8341
     Instance: 13000; Time: 5.26s; loss: 393.7457; acc: 148514/178056=0.8341
     Instance: 13500; Time: 5.70s; loss: 444.4959; acc: 154245/184981=0.8338
     Instance: 14000; Time: 5.38s; loss: 411.1087; acc: 159572/191452=0.8335
     Instance: 14500; Time: 5.20s; loss: 397.2859; acc: 165118/198095=0.8335
     Instance: 14986; Time: 5.40s; loss: 389.1057; acc: 170523/204566=0.8336
Epoch: 1 training finished. Time: 164.81s, speed: 90.93st/s,  total loss: 12719.768818855286
totalloss: 12719.768818855286
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.16s, speed: 564.23st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.80s, speed: 638.96st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000
Epoch: 2/100
 Learning rate is set as: 0.013636363636363634
Shuffle: first input word list: [2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
     Instance: 500; Time: 5.41s; loss: 436.1395; acc: 5824/7012=0.8306
     Instance: 1000; Time: 5.48s; loss: 385.2749; acc: 11357/13599=0.8351
     Instance: 1500; Time: 5.53s; loss: 415.0793; acc: 17094/20450=0.8359
     Instance: 2000; Time: 5.55s; loss: 413.8247; acc: 22636/27161=0.8334
     Instance: 2500; Time: 5.40s; loss: 420.5595; acc: 28451/34152=0.8331
     Instance: 3000; Time: 5.18s; loss: 362.7070; acc: 33769/40470=0.8344
     Instance: 3500; Time: 5.71s; loss: 408.6057; acc: 39442/47317=0.8336
     Instance: 4000; Time: 5.42s; loss: 415.7353; acc: 45278/54329=0.8334
     Instance: 4500; Time: 5.26s; loss: 390.8038; acc: 50917/61030=0.8343
     Instance: 5000; Time: 5.49s; loss: 410.7181; acc: 56446/67705=0.8337
     Instance: 5500; Time: 5.55s; loss: 417.0718; acc: 62245/74659=0.8337
     Instance: 6000; Time: 5.48s; loss: 416.0790; acc: 68118/81681=0.8340
     Instance: 6500; Time: 5.19s; loss: 404.0871; acc: 73511/88224=0.8332
     Instance: 7000; Time: 5.23s; loss: 430.6882; acc: 79219/95148=0.8326
     Instance: 7500; Time: 5.26s; loss: 414.4986; acc: 84977/102097=0.8323
     Instance: 8000; Time: 5.44s; loss: 372.8214; acc: 90537/108671=0.8331
     Instance: 8500; Time: 5.29s; loss: 376.0572; acc: 95977/115146=0.8335
     Instance: 9000; Time: 5.74s; loss: 393.9897; acc: 101715/122009=0.8337
     Instance: 9500; Time: 5.60s; loss: 444.6560; acc: 107654/129181=0.8334
     Instance: 10000; Time: 5.45s; loss: 422.0748; acc: 113211/135972=0.8326
     Instance: 10500; Time: 5.55s; loss: 415.9887; acc: 118967/142896=0.8325
     Instance: 11000; Time: 5.37s; loss: 392.2800; acc: 124211/149289=0.8320
     Instance: 11500; Time: 5.67s; loss: 405.8225; acc: 130222/156428=0.8325
     Instance: 12000; Time: 5.65s; loss: 414.1149; acc: 136121/163498=0.8326
     Instance: 12500; Time: 5.58s; loss: 410.7859; acc: 141971/170495=0.8327
     Instance: 13000; Time: 5.44s; loss: 406.8974; acc: 147548/177214=0.8326
     Instance: 13500; Time: 5.27s; loss: 398.6541; acc: 153373/184149=0.8329
     Instance: 14000; Time: 5.46s; loss: 404.1680; acc: 159096/190973=0.8331
     Instance: 14500; Time: 5.27s; loss: 383.6540; acc: 165023/197968=0.8336
     Instance: 14986; Time: 5.25s; loss: 397.4585; acc: 170523/204566=0.8336
Epoch: 2 training finished. Time: 163.20s, speed: 91.83st/s,  total loss: 12181.295450210571
totalloss: 12181.295450210571
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.18s, speed: 563.14st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.81s, speed: 637.34st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000
Epoch: 3/100
 Learning rate is set as: 0.013043478260869566
Shuffle: first input word list: [2, 2, 2, 2]
     Instance: 500; Time: 5.49s; loss: 401.5520; acc: 5588/6744=0.8286
     Instance: 1000; Time: 5.47s; loss: 423.1180; acc: 11382/13726=0.8292
     Instance: 1500; Time: 5.69s; loss: 397.5806; acc: 17080/20559=0.8308
     Instance: 2000; Time: 5.37s; loss: 402.0758; acc: 22700/27326=0.8307
     Instance: 2500; Time: 5.26s; loss: 373.3217; acc: 28362/34040=0.8332
     Instance: 3000; Time: 5.38s; loss: 382.8468; acc: 33965/40726=0.8340
     Instance: 3500; Time: 5.50s; loss: 377.1780; acc: 39843/47660=0.8360
     Instance: 4000; Time: 5.24s; loss: 395.6849; acc: 45476/54430=0.8355
     Instance: 4500; Time: 5.25s; loss: 400.7815; acc: 50939/61028=0.8347
     Instance: 5000; Time: 5.53s; loss: 401.5997; acc: 57020/68232=0.8357
     Instance: 5500; Time: 5.31s; loss: 384.0676; acc: 62393/74702=0.8352
     Instance: 6000; Time: 5.23s; loss: 418.5926; acc: 68060/81529=0.8348
     Instance: 6500; Time: 5.55s; loss: 428.4656; acc: 73992/88702=0.8342
     Instance: 7000; Time: 5.52s; loss: 424.5894; acc: 79857/95815=0.8334
     Instance: 7500; Time: 5.31s; loss: 385.3072; acc: 85075/102162=0.8327
     Instance: 8000; Time: 5.55s; loss: 396.4581; acc: 90761/108985=0.8328
     Instance: 8500; Time: 5.66s; loss: 360.9902; acc: 96596/115831=0.8339
     Instance: 9000; Time: 5.41s; loss: 387.4009; acc: 102245/122568=0.8342
     Instance: 9500; Time: 5.20s; loss: 387.1995; acc: 107829/129260=0.8342
     Instance: 10000; Time: 5.58s; loss: 426.1336; acc: 113663/136333=0.8337
     Instance: 10500; Time: 5.61s; loss: 390.8738; acc: 119387/143206=0.8337
     Instance: 11000; Time: 5.63s; loss: 422.8063; acc: 125286/150325=0.8334
     Instance: 11500; Time: 5.34s; loss: 387.0369; acc: 130685/156860=0.8331
     Instance: 12000; Time: 5.58s; loss: 396.0940; acc: 136412/163692=0.8333
     Instance: 12500; Time: 5.25s; loss: 367.3678; acc: 141830/170170=0.8335
     Instance: 13000; Time: 5.46s; loss: 387.3940; acc: 147733/177130=0.8340
     Instance: 13500; Time: 5.49s; loss: 405.8708; acc: 153590/184181=0.8339
     Instance: 14000; Time: 5.58s; loss: 407.3771; acc: 159170/190949=0.8336
     Instance: 14500; Time: 5.41s; loss: 380.1521; acc: 164731/197603=0.8336
     Instance: 14986; Time: 5.46s; loss: 409.9660; acc: 170522/204566=0.8336
Epoch: 3 training finished. Time: 163.31s, speed: 91.76st/s,  total loss: 11909.882559418678
totalloss: 11909.882559418678
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.23s, speed: 559.48st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.78s, speed: 639.40st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000
Epoch: 4/100
 Learning rate is set as: 0.0125
Shuffle: first input word list: [2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3]
     Instance: 500; Time: 5.45s; loss: 404.0416; acc: 5866/7016=0.8361
     Instance: 1000; Time: 5.30s; loss: 382.1240; acc: 11447/13708=0.8351
     Instance: 1500; Time: 5.42s; loss: 381.1682; acc: 16952/20317=0.8344
     Instance: 2000; Time: 5.23s; loss: 387.5546; acc: 22407/26895=0.8331
     Instance: 2500; Time: 5.16s; loss: 381.2725; acc: 27803/33383=0.8328
     Instance: 3000; Time: 5.33s; loss: 417.8431; acc: 33474/40260=0.8314
     Instance: 3500; Time: 5.40s; loss: 389.9610; acc: 39179/47080=0.8322
     Instance: 4000; Time: 5.62s; loss: 412.6207; acc: 45268/54354=0.8328
     Instance: 4500; Time: 5.53s; loss: 406.7833; acc: 51011/61310=0.8320
     Instance: 5000; Time: 5.39s; loss: 382.0359; acc: 56519/67895=0.8324
     Instance: 5500; Time: 5.06s; loss: 382.4959; acc: 61973/74477=0.8321
     Instance: 6000; Time: 5.46s; loss: 377.8582; acc: 67960/81522=0.8336
     Instance: 6500; Time: 5.27s; loss: 367.1264; acc: 73301/87945=0.8335
     Instance: 7000; Time: 5.19s; loss: 355.6229; acc: 78982/94648=0.8345
     Instance: 7500; Time: 5.44s; loss: 394.8074; acc: 84629/101438=0.8343
     Instance: 8000; Time: 5.37s; loss: 375.2287; acc: 90165/108049=0.8345
     Instance: 8500; Time: 5.71s; loss: 376.5849; acc: 95960/114906=0.8351
     Instance: 9000; Time: 5.66s; loss: 405.4678; acc: 101777/121910=0.8349
     Instance: 9500; Time: 5.18s; loss: 391.5243; acc: 107120/128427=0.8341
     Instance: 10000; Time: 5.39s; loss: 380.5630; acc: 112713/135117=0.8342
     Instance: 10500; Time: 5.81s; loss: 431.6293; acc: 118645/142308=0.8337
             Instance: 11000; Time: 5.37s; loss: 402.0669; acc: 124340/149140=0.8337
     Instance: 11500; Time: 5.63s; loss: 409.2975; acc: 130087/156080=0.8335
     Instance: 12000; Time: 5.36s; loss: 378.2141; acc: 135491/162592=0.8333
     Instance: 12500; Time: 5.42s; loss: 376.7511; acc: 141190/169413=0.8334
     Instance: 13000; Time: 5.36s; loss: 400.4109; acc: 146848/176215=0.8333
     Instance: 13500; Time: 5.53s; loss: 404.5539; acc: 152630/183183=0.8332
     Instance: 14000; Time: 5.68s; loss: 401.6745; acc: 158861/190583=0.8336
     Instance: 14500; Time: 5.57s; loss: 413.2835; acc: 164735/197642=0.8335
     Instance: 14986; Time: 5.51s; loss: 391.3215; acc: 170524/204566=0.8336
Epoch: 4 training finished. Time: 162.79s, speed: 92.06st/s,  total loss: 11761.887456417084
totalloss: 11761.887456417084
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.23s, speed: 559.71st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.81s, speed: 638.25st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000
Epoch: 5/100
 Learning rate is set as: 0.012
Shuffle: first input word list: [2, 2, 2, 2, 2]
     Instance: 500; Time: 5.66s; loss: 381.6468; acc: 5618/6734=0.8343
     Instance: 1000; Time: 5.42s; loss: 400.6623; acc: 11431/13682=0.8355
     Instance: 1500; Time: 5.40s; loss: 384.2276; acc: 17341/20712=0.8372
     Instance: 2000; Time: 5.25s; loss: 356.9555; acc: 22822/27231=0.8381
     Instance: 2500; Time: 5.37s; loss: 364.6856; acc: 28444/33907=0.8389
     Instance: 3000; Time: 5.56s; loss: 416.1254; acc: 34933/41557=0.8406
     Instance: 3500; Time: 5.26s; loss: 381.0427; acc: 40571/48293=0.8401
     Instance: 4000; Time: 5.57s; loss: 398.7148; acc: 46353/55262=0.8388
     Instance: 4500; Time: 5.44s; loss: 402.5182; acc: 52054/62129=0.8378
     Instance: 5000; Time: 5.19s; loss: 385.0131; acc: 57506/68698=0.8371
     Instance: 5500; Time: 5.38s; loss: 390.2033; acc: 63247/75573=0.8369
     Instance: 6000; Time: 5.39s; loss: 383.5077; acc: 68634/82073=0.8363
     Instance: 6500; Time: 5.45s; loss: 382.4222; acc: 74221/88769=0.8361
     Instance: 7000; Time: 5.37s; loss: 383.9613; acc: 80011/95671=0.8363
             Instance: 7500; Time: 5.45s; loss: 384.6937; acc: 85412/102232=0.8355
     Instance: 8000; Time: 5.68s; loss: 378.3377; acc: 91017/108940=0.8355
     Instance: 8500; Time: 5.64s; loss: 370.2925; acc: 96633/115631=0.8357
     Instance: 9000; Time: 5.49s; loss: 408.3350; acc: 102144/122371=0.8347
     Instance: 9500; Time: 5.56s; loss: 403.2952; acc: 107538/128995=0.8337
     Instance: 10000; Time: 5.42s; loss: 362.4672; acc: 113294/135794=0.8343
     Instance: 10500; Time: 5.35s; loss: 356.3109; acc: 118877/142433=0.8346
     Instance: 11000; Time: 5.50s; loss: 406.9036; acc: 124881/149641=0.8345
     Instance: 11500; Time: 5.48s; loss: 390.2478; acc: 130577/156486=0.8344
     Instance: 12000; Time: 5.56s; loss: 402.3553; acc: 136459/163544=0.8344
     Instance: 12500; Time: 5.40s; loss: 382.0685; acc: 142281/170469=0.8346
     Instance: 13000; Time: 5.74s; loss: 445.6279; acc: 148165/177684=0.8339
     Instance: 13500; Time: 5.15s; loss: 389.8673; acc: 153435/184116=0.8334
     Instance: 14000; Time: 5.53s; loss: 417.4627; acc: 159433/191332=0.8333
     Instance: 14500; Time: 5.19s; loss: 365.1926; acc: 164977/197924=0.8335
     Instance: 14986; Time: 5.24s; loss: 381.3668; acc: 170524/204566=0.8336
Epoch: 5 training finished. Time: 163.08s, speed: 91.89st/s,  total loss: 11656.511207222939
totalloss: 11656.511207222939
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.21s, speed: 562.23st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.77s, speed: 642.81st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000
Epoch: 6/100
 Learning rate is set as: 0.011538461538461537
Shuffle: first input word list: [2, 2, 2]
     Instance: 500; Time: 5.48s; loss: 401.9486; acc: 5781/6965=0.8300
     Instance: 1000; Time: 5.62s; loss: 384.5986; acc: 11536/13845=0.8332
     Instance: 1500; Time: 5.51s; loss: 417.3854; acc: 17780/21308=0.8344
     Instance: 2000; Time: 5.65s; loss: 393.7084; acc: 23749/28397=0.8363
     Instance: 2500; Time: 5.35s; loss: 370.2277; acc: 29072/34825=0.8348
     Instance: 3000; Time: 5.30s; loss: 349.6673; acc: 34605/41363=0.8366
     Instance: 3500; Time: 5.32s; loss: 377.4291; acc: 40084/47947=0.8360
     Instance: 4000; Time: 5.33s; loss: 369.7106; acc: 45505/54460=0.8356
     Instance: 4500; Time: 5.75s; loss: 399.7611; acc: 51303/61446=0.8349
     Instance: 5000; Time: 5.33s; loss: 376.3262; acc: 57062/68271=0.8358
     Instance: 5500; Time: 5.10s; loss: 347.2517; acc: 62332/74578=0.8358
     Instance: 6000; Time: 5.23s; loss: 375.7463; acc: 67894/81244=0.8357
     Instance: 6500; Time: 5.36s; loss: 368.8458; acc: 73614/88035=0.8362
     Instance: 7000; Time: 5.55s; loss: 380.6469; acc: 79431/94975=0.8363
     Instance: 7500; Time: 5.43s; loss: 401.6817; acc: 85078/101798=0.8358
     Instance: 8000; Time: 5.60s; loss: 391.9794; acc: 91319/109161=0.8366
     Instance: 8500; Time: 5.53s; loss: 394.1160; acc: 97110/116108=0.8364
     Instance: 9000; Time: 5.34s; loss: 377.3278; acc: 102649/122766=0.8361
     Instance: 9500; Time: 5.46s; loss: 376.5606; acc: 107906/129159=0.8355
     Instance: 10000; Time: 5.62s; loss: 369.9259; acc: 113081/135448=0.8349
     Instance: 10500; Time: 5.52s; loss: 364.3385; acc: 118776/142220=0.8352
     Instance: 11000; Time: 5.25s; loss: 396.5493; acc: 124348/148986=0.8346
     Instance: 11500; Time: 5.75s; loss: 401.7784; acc: 130586/156383=0.8350
     Instance: 12500; Time: 5.41s; loss: 381.1171; acc: 141723/169843=0.8344
     Instance: 13000; Time: 5.46s; loss: 413.3094; acc: 147394/176781=0.8338
     Instance: 13500; Time: 5.59s; loss: 400.8582; acc: 153411/183974=0.8339
     Instance: 14000; Time: 5.29s; loss: 372.7107; acc: 159000/190650=0.8340
     Instance: 14500; Time: 5.47s; loss: 391.3594; acc: 164541/197357=0.8337
     Instance: 14986; Time: 5.59s; loss: 425.4650; acc: 170524/204566=0.8336
Epoch: 6 training finished. Time: 163.43s, speed: 91.70st/s,  total loss: 11572.986675977707
totalloss: 11572.986675977707
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.17s, speed: 562.71st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.78s, speed: 640.24st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000
Epoch: 7/100
 Learning rate is set as: 0.01111111111111111
Shuffle: first input word list: [2, 2, 2]
     Instance: 500; Time: 5.47s; loss: 374.9266; acc: 5570/6658=0.8366
     Instance: 1000; Time: 5.37s; loss: 362.9837; acc: 11014/13176=0.8359
     Instance: 1500; Time: 5.67s; loss: 386.5207; acc: 17108/20378=0.8395
     Instance: 2000; Time: 5.62s; loss: 389.0672; acc: 22785/27220=0.8371
     Instance: 2500; Time: 5.47s; loss: 382.5923; acc: 28687/34279=0.8369
     Instance: 3000; Time: 5.26s; loss: 368.1319; acc: 34190/40901=0.8359
     Instance: 3500; Time: 5.45s; loss: 393.2582; acc: 39740/47614=0.8346
     Instance: 4000; Time: 5.34s; loss: 392.7045; acc: 45394/54422=0.8341
     Instance: 4500; Time: 5.31s; loss: 377.3566; acc: 50738/60893=0.8332
     Instance: 5000; Time: 5.41s; loss: 376.6756; acc: 56354/67626=0.8333
     Instance: 5500; Time: 5.42s; loss: 389.5069; acc: 62048/74474=0.8331
     Instance: 6000; Time: 5.48s; loss: 390.0989; acc: 67624/81203=0.8328
     Instance: 6500; Time: 5.69s; loss: 403.9725; acc: 73701/88454=0.8332
     Instance: 7000; Time: 5.58s; loss: 382.9669; acc: 79345/95223=0.8333
     Instance: 7500; Time: 5.52s; loss: 385.3155; acc: 85046/102050=0.8334
     Instance: 8000; Time: 5.37s; loss: 371.5117; acc: 90620/108739=0.8334
     Instance: 8500; Time: 5.53s; loss: 390.2922; acc: 96421/115696=0.8334
     Instance: 9000; Time: 5.51s; loss: 375.7071; acc: 101971/122356=0.8334
     Instance: 9500; Time: 5.29s; loss: 368.7694; acc: 107760/129228=0.8339
     Instance: 10000; Time: 5.38s; loss: 355.8612; acc: 113385/135885=0.8344
     Instance: 10500; Time: 5.19s; loss: 381.4508; acc: 119086/142691=0.8346
     Instance: 11000; Time: 5.58s; loss: 412.3629; acc: 124810/149675=0.8339
     Instance: 11500; Time: 5.66s; loss: 386.1944; acc: 130869/156865=0.8343
     Instance: 12000; Time: 5.53s; loss: 401.3127; acc: 136732/163900=0.8342
     Instance: 12500; Time: 5.58s; loss: 404.7056; acc: 142454/170845=0.8338
     Instance: 13000; Time: 5.33s; loss: 395.0213; acc: 147989/177557=0.8335
     Instance: 13500; Time: 5.34s; loss: 366.7315; acc: 153658/184281=0.8338
     Instance: 14000; Time: 5.26s; loss: 359.2290; acc: 159212/190901=0.8340
     Instance: 14500; Time: 5.52s; loss: 375.3674; acc: 164716/197525=0.8339
     Instance: 14986; Time: 5.51s; loss: 417.3557; acc: 170520/204566=0.8336
Epoch: 7 training finished. Time: 163.63s, speed: 91.58st/s,  total loss: 11517.950781226158
totalloss: 11517.950781226158
Right token =  42974  All token =  51577  acc =  0.8332008453380383
Dev: time: 6.18s, speed: 563.97st/s; acc: 0.8332, p: -1.0000, r: 0.0000, f: -1.0000
Right token =  38553  All token =  46665  acc =  0.8261652201864352
Test: time: 5.90s, speed: 627.84st/s; acc: 0.8262, p: -1.0000, r: 0.0000, f: -1.0000

**Comment by jiesutd** [comment]
Your `Word alphabet size: 5` is only 5, I am sure this is because of your data format is incorrect. Please check your data format should be the same as https://github.com/jiesutd/NCRFpp/blob/master/sample_data/train.bmes

**Comment by vidhishanair** [comment]
Thank you for the quick response! I was able to find my issue from this.
My BIO dataset had word id as the first column.
