### ISSUE TITLE
Can we use FastText embeddings as input?

### ISSUE THREAD

**Issue by Yugioh1984** [jiesutd/NCRFpp#101]
Hello,
Thank you for providing this amazing framework to the community.
I have a question related to input vectors? 
Could I use FastText embeddings instead of Word2vec/Glove embeddings?
Also, could I use this framework for other languages like Arabic, Turkish or Czech for example or it supports English only?

**Comment by jiesutd** [comment]
Hi @Yugioh1984 , any embedding can be accepted. It can be used in any language, just follow the same data format as the sample data.
