### ISSUE TITLE
When i run in decode status , i get  RuntimeError invalid argument 5: k not in range for dimension

### ISSUE THREAD

**Issue by zhengyima** [jiesutd/NCRFpp#102]
(torch) zhengyi_ma@ubuntu:~/NCRFpp-ner-2/NCRFpp$ python main.py --config demo.decode.config 
Seed num: 42
MODEL: decode
sample_data/mytest.bmes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DATA SUMMARY START:
 I/O:
     Start   Sequence   Laebling   task...
     Tag          scheme: BMES
     Split         token:  ||| 
     MAX SENTENCE LENGTH: 250
     MAX   WORD   LENGTH: -1
     Number   normalized: True
     Word  alphabet size: 375876
     Char  alphabet size: 8168
     Label alphabet size: 6
     Word embedding  dir: sample_data/sgns.baidubaike.bigram-char
     Char embedding  dir: None
     Word embedding size: 300
     Char embedding size: 30
     Norm   word     emb: False
     Norm   char     emb: False
     Train  file directory: sample_data/mytrain.bmes
     Dev    file directory: sample_data/mydev.bmes
     Test   file directory: sample_data/mytest.bmes
     Raw    file directory: sample_data/mytest.bmes
     Dset   file directory: sample_data/lstmcrf.dset
     Model  file directory: sample_data/lstmcrf
     Loadmodel   directory: sample_data/lstmcrf.7.model
     Decode file directory: sample_data/raw.out
     Train instance number: 149900
     Dev   instance number: 21623
     Test  instance number: 23099
     Raw   instance number: 0
     FEATURE num: 1
         Fe: [POS]  alphabet  size: 9292
         Fe: [POS]  embedding  dir: None
         Fe: [POS]  embedding size: 20
         Fe: [POS]  norm       emb: False
 ++++++++++++++++++++++++++++++++++++++++
 Model Network:
     Model        use_crf: True
     Model word extractor: LSTM
     Model       use_char: True
     Model char extractor: CNN
     Model char_hidden_dim: 50
 ++++++++++++++++++++++++++++++++++++++++
 Training:
     Optimizer: SGD
     Iteration: 25
     BatchSize: 10
     Average  batch   loss: False
 ++++++++++++++++++++++++++++++++++++++++
 Hyperparameters:
     Hyper              lr: 0.015
     Hyper        lr_decay: 0.05
     Hyper         HP_clip: None
     Hyper        momentum: 0.0
     Hyper              l2: 1e-08
     Hyper      hidden_dim: 200
     Hyper         dropout: 0.5
     Hyper      lstm_layer: 1
     Hyper          bilstm: True
     Hyper             GPU: True
DATA SUMMARY END.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
nbest: 10
Load Model from file:  sample_data/lstmcrf
build sequence labeling network...
use_char:  True
char feature extractor:  CNN
word feature extractor:  LSTM
use crf:  True
build word sequence feature extractor: LSTM...
build word representation...
build char sequence feature extractor: CNN ...
build CRF...
Decode raw data, nbest: 10 ...
Traceback (most recent call last):
  File "main.py", line 573, in <module>
    decode_results, pred_scores = load_model_decode(data, 'raw')
  File "main.py", line 502, in load_model_decode
    speed, acc, p, r, f, pred_results, pred_scores = evaluate(data, model, name, data.nbest)
  File "main.py", line 171, in evaluate
    scores, nbest_tag_seq = model.decode_nbest(batch_word,batch_features, batch_wordlen, batch_char, batch_charlen, batch_charrecover, mask, nbest)
  File "/home/zhengyi_ma/NCRFpp-ner-2/NCRFpp/model/seqlabel.py", line 81, in decode_nbest
    scores, tag_seq = self.crf._viterbi_decode_nbest(outs, mask, nbest)
  File "/home/zhengyi_ma/NCRFpp-ner-2/NCRFpp/model/crf.py", line 318, in _viterbi_decode_nbest
    partition, cur_bp = torch.topk(cur_values, nbest, 1)
RuntimeError: invalid argument 5: k not in range for dimension at /opt/conda/conda-bld/pytorch_1550784378911/work/aten/src/THC/generic/THCTensorTopK.cu:21

anyone get this error ?

**Comment by zhengyima** [comment]
i find that when i change "nbest = 10" to "nbest = 6" ,  the code works fine.

**Comment by jiesutd** [comment]
This is because your label alphabet only have 6 labels, so it can not generate 10 best, 6 best is the unbound.
