### ISSUE TITLE
求助，ACC计算

### ISSUE THREAD

**Issue by zgzjdx** [jiesutd/NCRFpp#103]
你好！感觉您分享的代码
目前我在做一些实验，想更改一下ACC的计算方式。对metric.py内的函数get_ner_fmeasure内的for idx in range(0,sent_num)的循环体进行了改动，但实验后ACC并没有发生改变，您能否给我一些建议，是否要对其它地方进行改动。我的语料是中文BIO标注的，目前测试集能在NCRF++上得到78%的ACC，还在进一步调参，这方面能否给些建议，万分感谢！！！

**Comment by jiesutd** [comment]
不知道你怎么改动的不知道给啥建议啊。还有就是确认是不是该对函数了，有几个函数名挺相似的

**Comment by zgzjdx** [comment]
是改错函数了，抱歉。
