### ISSUE TITLE
Training on new data

### ISSUE THREAD

**Issue by junaidamk** [jiesutd/NCRFpp#104]
Hi,
I tried this for our language Malayalam pos tagging by creating different models. I got best accuracy approx 87% with soft+ LSTM+LSTM model for 30000 (24000 train, 300 Dec,and 3000 test) pos tagged instances without embeddings. Could please help me to make sure my experiments are correct or not ? Also this data set is enouph for my experiments? Any suggestions please ..

Hyper-parameter Value
character dimension 50
word dimension 200
update function SGD
learning rate 0.05
learning decay rate 0.05
dropout rate 0.5
lstm-layer 1
batch size 10
iterations 10
gpu False

**Comment by jiesutd** [comment]
Hi, I would be happy to help. Please send me more details as well as your running log.

**Comment by junaidamk** [comment]
Thank you for your quick response...........
My log file link is attached here 
https://drive.google.com/open?id=14haP2-wWNWEC-_iNSTdgvk2eqi9uz7qE
Our Malayalam is low resource language and agglutinative language(https://en.wikipedia.org/wiki/Malayalam). Some machine learning approaches are tried on limitted corpus and full fledged pos tagger is not yet available.
Here i used general domain corpus constructed under Indian Language Corpora Initiative project.

**Comment by junaidamk** [comment]
> Hi, I would be happy to help. Please send me more details as well as your running log.

**Comment by junaidamk** [comment]
Thank you for your quick response...........
My log file link is attached here
https://drive.google.com/open?id=14haP2-wWNWEC-_iNSTdgvk2eqi9uz7qE
Our Malayalam is low resource language and agglutinative language(https://en.wikipedia.org/wiki/Malayalam). Some machine learning approaches are tried on limitted corpus and full fledged pos tagger is not yet available.
Here i used general domain corpus constructed under Indian Language Corpora Initiative project. Also i would like to use facebook fasttext Malayalam pre trained word embedding also..

**Comment by jiesutd** [comment]
Based on the log it seems everything is alright. 

If you want to tune the result, here are some suggestions:
1. Notice, based on the log, you are using learning rate 0.015 rather than 0.05
2. You can try to use CRF which may give a better result
3. You can also try to set the character level encoding as CNN rather LSTM.
4. As you said, the use of pretrained embedding would significantly improve the final result.

**Comment by junaidamk** [comment]
K... I have implemented all models listed below.
CCNN+WLSTM+CRF 85.40
CLSTM+WLSTM+CRF 86.94
NOCHAR+WLSTM+CRF 81.10
CCNN+WLSTM+SOFT 85.20
CLSTM+WLSTM+SOFT 87.05
NOCHAR+WLSTM+SOFT 81.
 How can I use pretrained fastext embedding for this experiment

Junaida M K
Research Scholar
Kannur University
mob:9497457586

**Comment by jiesutd** [comment]
Just load the pretrained embedding by setting the `word_emb_dir=xxx`, you may see the below link for the configuration settings:
https://github.com/jiesutd/NCRFpp/blob/master/readme/Configuration.md

**Comment by junaidamk** [comment]
K..is this dataset(31000 tagged instances) is enough to improve the
accuracy with pretrained embedding.

Junaida M K
Research Scholar
Kannur University
mob:9497457586

**Comment by jiesutd** [comment]
The pretrained embeddings are not necessary on your training data, it can be any big corpus in the language you investigate. Even you use your training data to train the embeddings, it would be beneficial to your final task.

**Comment by junaidamk** [comment]
Th big tagged corpus in our language is a one of the main problem we are facing. So I think transfer based learning will help to our language. That's why I mentioned pre trained fasttext crwal embedding.? Is this true for less resource language? 
Big corpus means what is the minimum size of the corpus?

**Comment by jiesutd** [comment]
Pretrained word embedding does not need tagged corpus. Only the raw text in your language is enough.

**Comment by junaidamk** [comment]
I also tried with glove embeddings on malayalam raw text (with 1103134 words). But s no improvement in accuracy.The log file is attached here.
https://drive.google.com/open?id=1c4rhTOW8pENBVRAi0R7yJbhKfBkjIM9U

**Comment by jiesutd** [comment]
You can try different embeddings. Generally speaking, the pretrained embeddings is very helpful. On the other hand, it should depends on the task.

**Comment by junaidamk** [comment]
K..I will try as soon as possible. Thank you.......

**Comment by junaidamk** [comment]
K..Thank you.......
I tried with fasttext malayalam 300 dimension embedding. I got this error?How can i resolve
Traceback (most recent call last):
  File "main.py", line 526, in <module>
    data.build_pretrain_emb()
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/data.py", line 287, in build_pretrain_emb
    self.pretrain_word_embedding, self.word_emb_dim = build_pretrain_embedding(self.word_emb_dir, self.word_alphabet, self.word_emb_dim, self.norm_word_emb)
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/functions.py", line 165, in build_pretrain_embedding
    embedd_dict, embedd_dim = load_pretrain_emb(embedding_path)
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/functions.py", line 208, in load_pretrain_emb
    assert (embedd_dim + 1 == len(tokens))
AssertionError

**Comment by junaidamk** [comment]
K..Thank you.......
I tried with fasttext malayalam 300 dimension embedding. I got this error?How can i resolve
Traceback (most recent call last):
  File "main.py", line 526, in <module>
    data.build_pretrain_emb()
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/data.py", line 287, in build_pretrain_emb
    self.pretrain_word_embedding, self.word_emb_dim = build_pretrain_embedding(self.word_emb_dir, self.word_alphabet, self.word_emb_dim, self.norm_word_emb)
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/functions.py", line 165, in build_pretrain_embedding
    embedd_dict, embedd_dim = load_pretrain_emb(embedding_path)
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/functions.py", line 208, in load_pretrain_emb
    assert (embedd_dim + 1 == len(tokens))
AssertionError

**Comment by jiesutd** [comment]
Open and check your embeddings file first.

**Comment by junaidamk** [comment]
K..Thank you.......
I tried with fasttext malayalam 300 dimension embedding. I got this error?How can i resolve
Traceback (most recent call last):
  File "main.py", line 526, in <module>
    data.build_pretrain_emb()
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/data.py", line 287, in build_pretrain_emb
    self.pretrain_word_embedding, self.word_emb_dim = build_pretrain_embedding(self.word_emb_dir, self.word_alphabet, self.word_emb_dim, self.norm_word_emb)
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/functions.py", line 165, in build_pretrain_embedding
    embedd_dict, embedd_dim = load_pretrain_emb(embedding_path)
  File "/home/junaida/ILCIL_PHASEII/NCRFpp-malayalam/utils/functions.py", line 208, in load_pretrain_emb
    assert (embedd_dim + 1 == len(tokens))
AssertionError

**Comment by junaidamk** [comment]
first line represents embedding size and dimension.
in my case 2000000 300
is it problem with this tool?

**Comment by jiesutd** [comment]
Remove it

**Comment by junaidamk** [comment]
Again same error after removing that line...

**Comment by jiesutd** [comment]
This is error is caused by that your embeddings does not have the same dimension in all lines of the file. Please check you embeddings file and debug by yourself. It should be a simple problem.

**Comment by junaidamk** [comment]
Ya..I corrected it.. but this time memory error...

**Comment by jiesutd** [comment]
You will solve it. It’s not complicate.

**Comment by junaidamk** [comment]
By making change to embedd_dim=300 in function.py worked for me.
def build_pretrain_embedding(embedding_path, word_alphabet, embedd_dim=300, norm=True):

**Comment by junaidamk** [comment]
hello.........if you feel free to reply I need some more clarification regarding my task..
i have trained with pretrained fasttext embedding, which also gives very little improvement in accuracy?
what i can try to improve the model accuracy? any suggesion please......

**Comment by junaidamk** [comment]
log file attached..........
[LSTM_LSTM_CRF_sgd_fast_emb.log](https://github.com/jiesutd/NCRFpp/files/3115486/LSTM_LSTM_CRF_sgd_fast_emb.log)

**Comment by QxMinfzl** [comment]
https://github.com/jiesutd/ncrfpp/issues/104#issuecomment-480487992
你好，我也遇到了这个问题一直不知道怎么解决，嵌入文件在哪里呢？
