### ISSUE TITLE
结果正确率问题

### ISSUE THREAD

**Issue by 0plusX** [jiesutd/NCRFpp#109]
你好，我用你的模型跑了13个epoch后对best model解码raw_data是测试集，用评测工具对结果评价，发现p、r、f1都较低：
processed 173615 tokens with 6145 phrases; found: 5280 phrases; correct: 1057.
accuracy:  80.64%; precision:  20.02%; recall:  17.20%; FB1:  18.50
              LOC: precision:  21.13%; recall:  20.13%; FB1:  20.62  2721
              ORG: precision:  17.99%; recall:  16.99%; FB1:  17.48  1256
              PER: precision:  19.65%; recall:  13.07%; FB1:  15.70  1303

为何在训练中测试集的p、r、f那么高，但评测后这么低呢?
评测工具为conlleval.pl
-------------------------------------------------------------
log:

Seed num: 42
MODEL: train
Find feature:  [pos]
Find feature:  [wb]
Load pretrained word embedding, norm: True, dir: sample_data/char_vec.txt
Embedding:
     pretrain word:4769, prefect match:4756, case_match:0, oov:67, oov%:0.013888888888888888
Training model...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DATA SUMMARY START:
 I/O:
     Start   Sequence   Laebling   task...
     Tag          scheme: BIO
     Split         token:  ||| 
     MAX SENTENCE LENGTH: 1000
     MAX   WORD   LENGTH: -1
     Number   normalized: True
     Word  alphabet size: 4824
     Char  alphabet size: 4826
     Label alphabet size: 8
     Word embedding  dir: sample_data/char_vec.txt
     Char embedding  dir: None
     Word embedding size: 100
     Char embedding size: 50
     Norm   word     emb: True
     Norm   char     emb: False
     Train  file directory: sample_data/2f.train
     Dev    file directory: sample_data/2f.dev
     Test   file directory: sample_data/2f.test
     Raw    file directory: None
     Dset   file directory: None
     Model  file directory: sample_data/lstmcrf
     Loadmodel   directory: None
     Decode file directory: None
     Train instance number: 45000
     Dev   instance number: 4537
     Test  instance number: 3441
     Raw   instance number: 0
     FEATURE num: 2
         Fe: [pos]  alphabet  size: 61
         Fe: [pos]  embedding  dir: None
         Fe: [pos]  embedding size: 20
         Fe: [pos]  norm       emb: False
         Fe: [wb]  alphabet  size: 7
         Fe: [wb]  embedding  dir: None
         Fe: [wb]  embedding size: 20
         Fe: [wb]  norm       emb: False
 ++++++++++++++++++++++++++++++++++++++++
 Model Network:
     Model        use_crf: True
     Model word extractor: LSTM
     Model       use_char: False
 ++++++++++++++++++++++++++++++++++++++++
 Training:
     Optimizer: adagrad
     Iteration: 1000
     BatchSize: 64
     Average  batch   loss: True
 ++++++++++++++++++++++++++++++++++++++++
 Hyperparameters:
     Hyper              lr: 0.015
     Hyper        lr_decay: 0.05
     Hyper         HP_clip: None
     Hyper        momentum: 0.0
     Hyper              l2: 1e-08
     Hyper      hidden_dim: 200
     Hyper         dropout: 0.5
     Hyper      lstm_layer: 1
     Hyper          bilstm: True
     Hyper             GPU: False
DATA SUMMARY END.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
build sequence labeling network...
use_char:  False
word feature extractor:  LSTM
use crf:  True
build word sequence feature extractor: LSTM...
build word representation...
build CRF...
Epoch: 0/1000
Shuffle: first input word list: [46, 108, 10, 725, 95, 97, 95, 95, 39, 1392, 795, 591, 687, 1208, 453, 191, 27, 28, 260, 702, 837, 417, 9, 29, 72, 198, 425, 375, 136, 731, 1092, 18, 497, 53, 530, 78, 38, 2248, 278, 1296, 53, 530, 1090, 770, 577, 1307, 9, 451, 96, 1088, 1068, 591, 1265, 345, 350, 217, 1306, 1688, 218, 191, 27, 96, 307, 308, 18, 544, 95, 96, 26, 65, 18, 135, 709, 307, 1912, 2986, 117, 145, 146, 1360, 363, 9, 266, 1116, 448, 345, 827, 265, 206, 813, 2981, 451, 96, 1088, 1068, 591, 18, 191, 348, 95, 354, 95, 96, 9, 818, 1124, 53, 117, 848, 486, 20, 452, 278, 78, 270, 117, 19, 399, 117, 773, 185, 129, 266, 901, 9, 1210, 1211, 70]
     Instance: 8000; Time: 299.00s; loss: 1586.4518; acc: 360710.0/391012.0=0.9225
     Instance: 16000; Time: 252.92s; loss: 854.9906; acc: 726976.0/775678.0=0.9372
     Instance: 24000; Time: 239.02s; loss: 718.7530; acc: 1097478.0/1162269.0=0.9443
     Instance: 32000; Time: 272.94s; loss: 640.5142; acc: 1467619.0/1547160.0=0.9486
     Instance: 40000; Time: 237.99s; loss: 588.6535; acc: 1838839.0/1932301.0=0.9516
     Instance: 45000; Time: 140.48s; loss: 352.6502; acc: 2069830.0/2171573.0=0.9531
     Instance: 45000; Time: 0.34s; loss: 0.0000; acc: 2069830.0/2171573.0=0.9531
Epoch: 0 training finished. Time: 1442.69s, speed: 31.19st/s,  total loss: 4742.013214111328
totalloss: 4742.013214111328
Right token =  211777  All token =  217223  acc =  0.9749289900240766
Dev: time: 28.46s, speed: 160.45st/s; acc: 0.9749, p: 0.6666, r: 0.6413, f: 0.6537
Exceed previous best f score: -10
Save current best model in file: sample_data/lstmcrf.0.model
Right token =  164811  All token =  170174  acc =  0.9684851975037315
Test: time: 25.85s, speed: 133.99st/s; acc: 0.9685, p: 0.7245, r: 0.6901, f: 0.7069
Epoch: 1/1000
Shuffle: first input word list: [248, 18, 1549, 2511, 353, 60, 109, 942, 378, 1371, 3756, 18, 1549, 2389, 1408, 2212, 74, 1408, 382, 53, 9, 182, 317, 2866, 1299, 278, 822, 817, 83, 56, 18, 1238, 624, 1769, 1247, 9, 1769, 1242, 785, 689, 291, 122, 798, 18, 274, 47, 18, 378, 1371, 3756, 40, 307, 195, 154, 178, 55, 153, 1769, 1242, 167, 50, 18, 220, 135, 732, 1299, 236, 275, 180, 95, 95, 793, 3022, 135, 136, 70]
     Instance: 8000; Time: 227.76s; loss: 540.5916; acc: 374918.0/388321.0=0.9655
     Instance: 16000; Time: 287.22s; loss: 504.1164; acc: 751064.0/777062.0=0.9665
     Instance: 24000; Time: 218.37s; loss: 464.7418; acc: 1118086.0/1156130.0=0.9671
     Instance: 32000; Time: 244.40s; loss: 466.9012; acc: 1488194.0/1538504.0=0.9673
     Instance: 40000; Time: 272.75s; loss: 440.6490; acc: 1864421.0/1926563.0=0.9677
     Instance: 45000; Time: 209.71s; loss: 278.1708; acc: 2102140.0/2171573.0=0.9680
     Instance: 45000; Time: 0.10s; loss: 0.0000; acc: 2102140.0/2171573.0=0.9680
Epoch: 1 training finished. Time: 1460.32s, speed: 30.82st/s,  total loss: 2695.1707305908203
totalloss: 2695.1707305908203
Right token =  212894  All token =  217223  acc =  0.9800711711006661
Dev: time: 28.40s, speed: 160.81st/s; acc: 0.9801, p: 0.7604, r: 0.6979, f: 0.7278
Exceed previous best f score: 0.6536741946578012
Save current best model in file: sample_data/lstmcrf.1.model
Right token =  165455  All token =  170174  acc =  0.9722695593921515
Test: time: 25.68s, speed: 134.84st/s; acc: 0.9723, p: 0.7831, r: 0.7303, f: 0.7558
Epoch: 2/1000
Shuffle: first input word list: [324, 1901, 2372, 331, 1047, 488, 240, 184, 571, 1604, 145, 74, 96, 1726, 83, 56, 9, 309, 117, 484, 96, 495, 486, 185, 53, 1526, 1308, 95, 95, 149, 161, 486, 590, 1393, 9, 486, 185, 251, 1300, 1301, 887, 488, 9, 95, 95, 149, 486, 185, 61, 14, 1435, 8, 273, 1047, 70]
     Instance: 8000; Time: 265.00s; loss: 414.1249; acc: 373120.0/384562.0=0.9702
     Instance: 16000; Time: 296.40s; loss: 407.2514; acc: 748736.0/771391.0=0.9706
     Instance: 24000; Time: 304.65s; loss: 405.6964; acc: 1125830.0/1159816.0=0.9707
     Instance: 32000; Time: 297.83s; loss: 392.1353; acc: 1499516.0/1544834.0=0.9707
     Instance: 40000; Time: 258.83s; loss: 379.1874; acc: 1873266.0/1929417.0=0.9709
     Instance: 45000; Time: 144.59s; loss: 234.2878; acc: 2108992.0/2171573.0=0.9712
     Instance: 45000; Time: 0.18s; loss: 0.0000; acc: 2108992.0/2171573.0=0.9712
Epoch: 2 training finished. Time: 1567.48s, speed: 28.71st/s,  total loss: 2232.683151245117
totalloss: 2232.683151245117
Right token =  213443  All token =  217223  acc =  0.9825985277802074
Dev: time: 28.62s, speed: 159.66st/s; acc: 0.9826, p: 0.7836, r: 0.7337, f: 0.7578
Exceed previous best f score: 0.7278057933622609
Save current best model in file: sample_data/lstmcrf.2.model
Right token =  165913  All token =  170174  acc =  0.9749609223500653
Test: time: 26.10s, speed: 132.68st/s; acc: 0.9750, p: 0.7984, r: 0.7575, f: 0.7774
Epoch: 3/1000
Shuffle: first input word list: [1169, 964, 9, 39, 6, 475, 1256, 226, 162, 797, 257, 18, 1229, 178, 514, 53, 22, 455, 1192, 193, 40, 531, 514, 72, 238, 9, 964, 157, 431, 382, 178, 408, 299, 9, 2322, 599, 93, 351, 18, 584, 60, 610, 653, 642, 178, 931, 198, 53, 22, 78, 270, 516, 404, 9, 282, 203, 70]
     Instance: 8000; Time: 232.16s; loss: 364.5571; acc: 373455.0/384059.0=0.9724
     Instance: 16000; Time: 241.86s; loss: 341.3476; acc: 745776.0/766286.0=0.9732
     Instance: 24000; Time: 280.22s; loss: 335.9779; acc: 1124209.0/1154680.0=0.9736
     Instance: 32000; Time: 283.85s; loss: 358.8347; acc: 1501418.0/1542644.0=0.9733
     Instance: 40000; Time: 263.40s; loss: 352.5958; acc: 1879932.0/1931808.0=0.9731
     Instance: 45000; Time: 174.51s; loss: 217.0028; acc: 2113133.0/2171573.0=0.9731
     Instance: 45000; Time: 0.11s; loss: 0.0000; acc: 2113133.0/2171573.0=0.9731
Epoch: 3 training finished. Time: 1476.11s, speed: 30.49st/s,  total loss: 1970.3158416748047
totalloss: 1970.3158416748047
Right token =  213627  All token =  217223  acc =  0.9834455835708005
Dev: time: 28.09s, speed: 162.61st/s; acc: 0.9834, p: 0.7925, r: 0.7515, f: 0.7714
Exceed previous best f score: 0.7578115925194564
Save current best model in file: sample_data/lstmcrf.3.model
Right token =  165950  All token =  170174  acc =  0.9751783468684992
Test: time: 25.55s, speed: 135.54st/s; acc: 0.9752, p: 0.8023, r: 0.7703, f: 0.7860
Epoch: 4/1000
Shuffle: first input word list: [260, 47, 53, 22, 10, 96, 198, 199, 398, 129, 20, 452, 901, 273, 392, 503, 164, 1526, 415, 9, 29, 217, 822, 852, 18, 47, 1637, 577, 846, 577, 1724, 848, 1377, 514, 1088, 72, 274, 1143, 257, 132, 48, 29, 190, 111, 188, 544, 9, 85, 203, 56, 486, 18, 369, 317, 653, 251, 22, 390, 2298, 442, 9, 85, 91, 623, 596, 74, 392, 9, 118, 89, 26, 146, 9, 445, 246, 278, 195, 450, 18, 87, 47, 59, 22, 577, 1307, 19, 20, 21, 22, 415, 635, 117, 577, 198, 53, 123, 207, 1161, 1704, 56, 366, 21, 9, 85, 56, 2742, 1887, 70]
     Instance: 8000; Time: 277.93s; loss: 334.9919; acc: 380129.0/390202.0=0.9742
     Instance: 16000; Time: 271.79s; loss: 315.0048; acc: 757504.0/777026.0=0.9749
     Instance: 24000; Time: 269.80s; loss: 311.9272; acc: 1133465.0/1162616.0=0.9749
     Instance: 32000; Time: 235.91s; loss: 314.7539; acc: 1509071.0/1548080.0=0.9748
     Instance: 40000; Time: 216.21s; loss: 312.0599; acc: 1880446.0/1929213.0=0.9747
     Instance: 45000; Time: 157.34s; loss: 197.1122; acc: 2116945.0/2171573.0=0.9748
     Instance: 45000; Time: 0.18s; loss: 0.0000; acc: 2116945.0/2171573.0=0.9748
Epoch: 4 training finished. Time: 1429.16s, speed: 31.49st/s,  total loss: 1785.8500518798828
totalloss: 1785.8500518798828
Right token =  210553  All token =  217223  acc =  0.9692942275910009
Dev: time: 28.21s, speed: 161.89st/s; acc: 0.9693, p: 0.7008, r: 0.7528, f: 0.7259
Right token =  162041  All token =  170174  acc =  0.9522077403128563
Test: time: 25.63s, speed: 135.11st/s; acc: 0.9522, p: 0.7235, r: 0.7473, f: 0.7352
Epoch: 5/1000
Shuffle: first input word list: [259, 1590, 178, 18, 260, 47, 276, 22, 1180, 56, 9, 554, 1287, 166, 1296, 74, 188, 4468, 70]
     Instance: 8000; Time: 232.55s; loss: 306.9022; acc: 372532.0/382248.0=0.9746
     Instance: 16000; Time: 270.74s; loss: 284.7562; acc: 747907.0/766755.0=0.9754
     Instance: 24000; Time: 285.25s; loss: 295.1732; acc: 1126502.0/1154799.0=0.9755
     Instance: 32000; Time: 273.36s; loss: 291.7760; acc: 1505567.0/1543020.0=0.9757
     Instance: 40000; Time: 226.25s; loss: 291.5304; acc: 1881639.0/1928376.0=0.9758
     Instance: 45000; Time: 182.02s; loss: 171.9740; acc: 2119163.0/2171573.0=0.9759
     Instance: 45000; Time: 0.10s; loss: 0.0000; acc: 2119163.0/2171573.0=0.9759
Epoch: 5 training finished. Time: 1470.27s, speed: 30.61st/s,  total loss: 1642.1119689941406
totalloss: 1642.1119689941406
Right token =  214116  All token =  217223  acc =  0.9856967264055833
Dev: time: 28.29s, speed: 161.43st/s; acc: 0.9857, p: 0.8451, r: 0.7571, f: 0.7987
Exceed previous best f score: 0.7714153775109674
Save current best model in file: sample_data/lstmcrf.5.model
Right token =  166362  All token =  170174  acc =  0.9775993982629544
Test: time: 25.74s, speed: 134.51st/s; acc: 0.9776, p: 0.8398, r: 0.7770, f: 0.8072
Epoch: 6/1000
Shuffle: first input word list: [569, 280, 251, 624, 2102, 2483, 2484, 9, 72, 167, 964, 157, 55, 716, 47, 1568, 642, 171, 667, 1162, 382, 793, 2006, 9, 237, 238, 964, 157, 70]
     Instance: 8000; Time: 262.43s; loss: 274.2701; acc: 377686.0/386546.0=0.9771
     Instance: 16000; Time: 237.48s; loss: 271.5450; acc: 751968.0/769658.0=0.9770
     Instance: 24000; Time: 280.85s; loss: 270.2705; acc: 1130277.0/1156854.0=0.9770
     Instance: 32000; Time: 270.58s; loss: 266.4450; acc: 1507709.0/1543064.0=0.9771
     Instance: 40000; Time: 243.58s; loss: 273.1657; acc: 1885914.0/1930429.0=0.9769
     Instance: 45000; Time: 166.70s; loss: 167.4845; acc: 2121566.0/2171573.0=0.9770
     Instance: 45000; Time: 0.18s; loss: 0.0000; acc: 2121566.0/2171573.0=0.9770
Epoch: 6 training finished. Time: 1461.80s, speed: 30.78st/s,  total loss: 1523.180892944336
totalloss: 1523.180892944336
Right token =  214219  All token =  217223  acc =  0.9861708935057522
Dev: time: 28.41s, speed: 160.77st/s; acc: 0.9862, p: 0.8368, r: 0.7821, f: 0.8085
Exceed previous best f score: 0.7986712540040337
Save current best model in file: sample_data/lstmcrf.6.model
Right token =  166419  All token =  170174  acc =  0.9779343495481095
Test: time: 25.95s, speed: 133.46st/s; acc: 0.9779, p: 0.8355, r: 0.7947, f: 0.8146
Epoch: 7/1000
Shuffle: first input word list: [818, 1124, 9, 153, 2633, 280, 117, 1217, 1870, 280, 278, 551, 5, 280, 95, 95, 1883, 497, 342, 479, 191, 348, 18, 74, 2654, 206, 812, 1664, 398, 275, 95, 95, 1883, 70]
     Instance: 8000; Time: 247.24s; loss: 253.3324; acc: 381440.0/389921.0=0.9782
     Instance: 16000; Time: 286.34s; loss: 257.5703; acc: 760024.0/777107.0=0.9780
     Instance: 24000; Time: 265.89s; loss: 258.9609; acc: 1134505.0/1160540.0=0.9776
     Instance: 32000; Time: 286.05s; loss: 255.1125; acc: 1513505.0/1548190.0=0.9776
     Instance: 40000; Time: 227.32s; loss: 255.2852; acc: 1889785.0/1932885.0=0.9777
     Instance: 45000; Time: 151.64s; loss: 163.8296; acc: 2123051.0/2171573.0=0.9777
     Instance: 45000; Time: 0.09s; loss: 0.0000; acc: 2123051.0/2171573.0=0.9777
Epoch: 7 training finished. Time: 1464.56s, speed: 30.73st/s,  total loss: 1444.0909881591797
totalloss: 1444.0909881591797
Right token =  214289  All token =  217223  acc =  0.9864931429913039
Dev: time: 28.25s, speed: 161.64st/s; acc: 0.9865, p: 0.8320, r: 0.7987, f: 0.8150
Exceed previous best f score: 0.8085106382978723
Save current best model in file: sample_data/lstmcrf.7.model
Right token =  166360  All token =  170174  acc =  0.9775876455862823
Test: time: 25.62s, speed: 135.16st/s; acc: 0.9776, p: 0.8304, r: 0.8015, f: 0.8157
Epoch: 8/1000
Shuffle: first input word list: [300, 432, 154, 1559, 9, 53, 22, 479, 2863, 149, 1871, 248, 283, 540, 455, 571, 367, 329, 1704, 18, 369, 20, 1741, 511, 2264, 513, 18, 20, 1741, 2131, 1088, 1240, 117, 2412, 1704, 1180, 18, 571, 353, 95, 1294, 3308, 3309, 117, 95, 1294, 477, 3315, 117, 95, 1294, 181, 2235, 2230, 117, 95, 1294, 2419, 2009, 117, 95, 1294, 2419, 258, 1397, 117, 95, 1294, 893, 2447, 117, 95, 95, 1294, 1428, 217, 117, 95, 95, 1294, 181, 250, 2210, 117, 95, 95, 1294, 2179, 162, 162, 117, 95, 95, 1294, 854, 737, 117, 95, 95, 1294, 511, 3320, 122, 117, 95, 95, 1294, 274, 3312, 70]
     Instance: 8000; Time: 260.89s; loss: 249.9745; acc: 378210.0/386633.0=0.9782
     Instance: 16000; Time: 253.64s; loss: 239.8650; acc: 754222.0/770816.0=0.9785
     Instance: 24000; Time: 244.65s; loss: 239.4943; acc: 1132179.0/1157059.0=0.9785
     Instance: 32000; Time: 258.29s; loss: 238.7275; acc: 1510134.0/1543383.0=0.9785
     Instance: 40000; Time: 255.57s; loss: 247.0385; acc: 1889634.0/1931291.0=0.9784
     Instance: 45000; Time: 174.89s; loss: 159.2359; acc: 2124470.0/2171573.0=0.9783
     Instance: 45000; Time: 0.22s; loss: 0.0000; acc: 2124470.0/2171573.0=0.9783
Epoch: 8 training finished. Time: 1448.14s, speed: 31.07st/s,  total loss: 1374.335693359375
totalloss: 1374.335693359375
Right token =  214073  All token =  217223  acc =  0.9854987731501729
Dev: time: 28.62s, speed: 159.56st/s; acc: 0.9855, p: 0.8470, r: 0.7557, f: 0.7988
Right token =  165586  All token =  170174  acc =  0.9730393597141749
Test: time: 25.82s, speed: 134.08st/s; acc: 0.9730, p: 0.8161, r: 0.7503, f: 0.7818
Epoch: 9/1000
Shuffle: first input word list: [497, 325, 164, 2248, 117, 1178, 462, 1249, 2091, 952, 18, 2163, 30, 152, 266, 901, 199, 1247, 84, 2248, 353, 18, 1090, 14, 449, 375, 1178, 1179, 2248, 353, 375, 18, 1070, 1671, 273, 1767, 1750, 1224, 108, 431, 382, 543, 1334, 708, 510, 18, 225, 114, 26, 448, 1224, 108, 193, 241, 2812, 708, 510, 81, 1282, 70]
     Instance: 8000; Time: 252.97s; loss: 226.9855; acc: 373706.0/381690.0=0.9791
     Instance: 16000; Time: 204.65s; loss: 230.0659; acc: 749044.0/764994.0=0.9792
     Instance: 24000; Time: 227.49s; loss: 233.0966; acc: 1127953.0/1152088.0=0.9791
     Instance: 32000; Time: 282.76s; loss: 235.7867; acc: 1506578.0/1539036.0=0.9789
     Instance: 40000; Time: 307.61s; loss: 231.4924; acc: 1886241.0/1926802.0=0.9789
     Instance: 45000; Time: 181.43s; loss: 151.5118; acc: 2125720.0/2171573.0=0.9789
     Instance: 45000; Time: 0.14s; loss: 0.0000; acc: 2125720.0/2171573.0=0.9789
Epoch: 9 training finished. Time: 1457.05s, speed: 30.88st/s,  total loss: 1308.9389190673828
totalloss: 1308.9389190673828
Right token =  214500  All token =  217223  acc =  0.9874644950120384
Dev: time: 28.45s, speed: 160.51st/s; acc: 0.9875, p: 0.8485, r: 0.8027, f: 0.8250
Exceed previous best f score: 0.8150103282074821
Save current best model in file: sample_data/lstmcrf.9.model
Right token =  166521  All token =  170174  acc =  0.9785337360583873
Test: time: 25.72s, speed: 134.65st/s; acc: 0.9785, p: 0.8446, r: 0.8076, f: 0.8257
Epoch: 10/1000
Shuffle: first input word list: [56, 236, 348, 577, 1334, 38, 18, 325, 425, 9, 2298, 442, 74, 785, 56, 6, 233, 136, 1247, 198, 84, 19, 399, 9, 2298, 442, 70]
     Instance: 8000; Time: 265.88s; loss: 222.4381; acc: 379677.0/387575.0=0.9796
     Instance: 16000; Time: 278.53s; loss: 224.5166; acc: 760091.0/776150.0=0.9793
     Instance: 24000; Time: 238.49s; loss: 223.6321; acc: 1137837.0/1161706.0=0.9795
     Instance: 32000; Time: 254.93s; loss: 227.8724; acc: 1515157.0/1547246.0=0.9793
     Instance: 40000; Time: 272.89s; loss: 217.0261; acc: 1890553.0/1930450.0=0.9793
     Instance: 45000; Time: 170.78s; loss: 138.6168; acc: 2126778.0/2171573.0=0.9794
     Instance: 45000; Time: 0.09s; loss: 0.0000; acc: 2126778.0/2171573.0=0.9794
Epoch: 10 training finished. Time: 1481.59s, speed: 30.37st/s,  total loss: 1254.1020812988281
totalloss: 1254.1020812988281
Right token =  214629  All token =  217223  acc =  0.9880583547782693
Dev: time: 30.98s, speed: 147.33st/s; acc: 0.9881, p: 0.8629, r: 0.8068, f: 0.8339
Exceed previous best f score: 0.8250115580212668
Save current best model in file: sample_data/lstmcrf.10.model
Right token =  166694  All token =  170174  acc =  0.979550342590525
Test: time: 26.18s, speed: 132.24st/s; acc: 0.9796, p: 0.8530, r: 0.8075, f: 0.8296
Epoch: 11/1000
Shuffle: first input word list: [162, 22, 56, 117, 766, 162, 56, 278, 22, 207, 208, 129, 208, 813, 9, 451, 96, 1090, 770, 278, 513, 162, 486, 185, 56, 375, 239, 548, 193, 18, 1752, 28, 74, 1147, 3584, 1562, 448, 2405, 1756, 1562, 2664, 1982, 226, 921, 164, 165, 1459, 143, 178, 906, 2386, 18, 135, 1247, 190, 273, 1755, 689, 591, 9, 3508, 165, 70]
     Instance: 8000; Time: 285.10s; loss: 211.1272; acc: 380313.0/387858.0=0.9805
     Instance: 16000; Time: 268.76s; loss: 214.6739; acc: 758287.0/773522.0=0.9803
     Instance: 24000; Time: 325.18s; loss: 209.7188; acc: 1135616.0/1158515.0=0.9802
     Instance: 32000; Time: 258.09s; loss: 217.7040; acc: 1512803.0/1543532.0=0.9801
     Instance: 40000; Time: 288.31s; loss: 215.8403; acc: 1892153.0/1930661.0=0.9801
     Instance: 45000; Time: 172.24s; loss: 130.8118; acc: 2128347.0/2171573.0=0.9801
     Instance: 45000; Time: 0.17s; loss: 0.0000; acc: 2128347.0/2171573.0=0.9801
Epoch: 11 training finished. Time: 1597.86s, speed: 28.16st/s,  total loss: 1199.8760070800781
totalloss: 1199.8760070800781
Right token =  214688  All token =  217223  acc =  0.9883299650589487
Dev: time: 31.36s, speed: 145.51st/s; acc: 0.9883, p: 0.8679, r: 0.8099, f: 0.8379
Exceed previous best f score: 0.8338951528536557
Save current best model in file: sample_data/lstmcrf.11.model
Right token =  166671  All token =  170174  acc =  0.9794151868087957
Test: time: 26.81s, speed: 129.18st/s; acc: 0.9794, p: 0.8598, r: 0.8116, f: 0.8350
Epoch: 12/1000
Shuffle: first input word list: [300, 348, 171, 392, 347, 3005, 931, 49, 537, 135, 368, 18, 1988, 335, 1720, 398, 129, 486, 488, 5, 188, 2248, 353, 375, 91, 722, 261, 1720, 95, 95, 48, 398, 488, 95, 95, 11, 56, 486, 185, 18, 486, 740, 95, 149, 56, 486, 185, 1767, 931, 47, 162, 793, 38, 117, 1252, 738, 729, 143, 117, 314, 338, 193, 207, 1047, 682, 1239, 9, 1393, 661, 161, 235, 18, 514, 26, 307, 450, 178, 135, 324, 338, 454, 117, 729, 143, 18, 442, 869, 549, 503, 164, 1393, 661, 56, 486, 185, 331, 9, 369, 157, 566, 317, 70]
     Instance: 8000; Time: 235.12s; loss: 208.8093; acc: 375896.0/383644.0=0.9798
     Instance: 16000; Time: 277.37s; loss: 207.2930; acc: 755929.0/771413.0=0.9799
     Instance: 24000; Time: 286.95s; loss: 205.1098; acc: 1133844.0/1156868.0=0.9801
     Instance: 32000; Time: 248.53s; loss: 205.7095; acc: 1515016.0/1545549.0=0.9802
     Instance: 40000; Time: 236.95s; loss: 207.1384; acc: 1892844.0/1931009.0=0.9802
     Instance: 45000; Time: 168.23s; loss: 128.2052; acc: 2128749.0/2171573.0=0.9803
     Instance: 45000; Time: 0.12s; loss: 0.0000; acc: 2128749.0/2171573.0=0.9803
Epoch: 12 training finished. Time: 1453.26s, speed: 30.96st/s,  total loss: 1162.2650909423828
totalloss: 1162.2650909423828
Right token =  214675  All token =  217223  acc =  0.9882701187259176
Dev: time: 28.42s, speed: 160.68st/s; acc: 0.9883, p: 0.8760, r: 0.8041, f: 0.8385
Exceed previous best f score: 0.8379290285049449
Save current best model in file: sample_data/lstmcrf.12.model
Right token =  166815  All token =  170174  acc =  0.9802613795291878
Test: time: 25.66s, speed: 134.99st/s; acc: 0.9803, p: 0.8685, r: 0.8105, f: 0.8385
Epoch: 13/1000
Shuffle: first input word list: [300, 485, 55, 28, 18, 410, 1452, 546, 250, 454, 9, 95, 3208, 454, 3394, 87, 1023, 299, 88, 1990, 9, 533, 192, 379, 343, 70]
     Instance: 8000; Time: 262.30s; loss: 200.5388; acc: 379833.0/387317.0=0.9807
     Instance: 16000; Time: 277.50s; loss: 201.5161; acc: 759113.0/774017.0=0.9807
     Instance: 24000; Time: 234.44s; loss: 196.7661; acc: 1136447.0/1158779.0=0.9807
     Instance: 32000; Time: 247.29s; loss: 203.0335; acc: 1516604.0/1546681.0=0.9806
     Instance: 40000; Time: 265.18s; loss: 194.8583; acc: 1893686.0/1930949.0=0.9807
     Instance: 45000; Time: 171.57s; loss: 130.8293; acc: 2129455.0/2171573.0=0.9806
     Instance: 45000; Time: 0.16s; loss: 0.0000; acc: 2129455.0/2171573.0=0.9806
Epoch: 13 training finished. Time: 1458.44s, speed: 30.85st/s,  total loss: 1127.5420989990234
totalloss: 1127.5420989990234
Right token =  214755  All token =  217223  acc =  0.9886384038522624
Dev: time: 28.37s, speed: 160.96st/s; acc: 0.9886, p: 0.8657, r: 0.8207, f: 0.8426
Exceed previous best f score: 0.8385129588366365
Save current best model in file: sample_data/lstmcrf.13.model
Right token =  166675  All token =  170174  acc =  0.97943869216214
Test: time: 25.75s, speed: 134.50st/s; acc: 0.9794, p: 0.8576, r: 0.8154, f: 0.8360

**Comment by jiesutd** [comment]
能否把你的测试数据发给我，我来试试

**Comment by 0plusX** [comment]
已发送至你的邮箱，麻烦查收一下

**Comment by jiesutd** [comment]
@0plusX 我知道原因了。我查看了你的`2f.test`文件，发现里面有一个长度为2427的句子。然而你的设置是`MAX SENTENCE LENGTH: 1000`, 因此这个超过1000的长句子被扔掉了。
这就导致你用conlleval.pl 和原始文件对比时长度匹配不上，从长句子以后的部分全部没有对齐，导致结果很低。

你可以尝试： 
1. 设置Max Sentence Length = 2500 或者
2.  找到这个长句子删掉， 或者
3. 手动把这个长句子分成几个短的句子。

**Comment by 0plusX** [comment]
感谢你的帮助~~
