### ISSUE TITLE
Loading pre-trained embeddings

### ISSUE THREAD

**Issue by taasmoe** [jiesutd/NCRFpp#111]
Hi!

Thank you for making this toolkit available!

I have a collection of pre-trained embeddings with different vector sizes, and I have a question regarding the **word_emb_dim** setting in the configuration file.

Let's say we load a 300-dimensional pre-trained embedding, and keep the default **word_emb_dim** value, which is 50. What will happen then? Will **word_emb_dim** be overridden?

**Comment by jiesutd** [comment]
Yes, it will be overwritten as the real pretrain embeddings size.

**Comment by taasmoe** [comment]
Thank you! :+1:
