### ISSUE TITLE
is it useful of 'acc' result when decoding raw data?

### ISSUE THREAD

**Issue by Biaocsu** [jiesutd/NCRFpp#115]
When I use this awesome pro, I found that when I decode the model with different raw data, I get results in below which makes me confused. like:
result (1)
build CRF...
Decode raw data, nbest: 1 ...
gold_num =  0  pred_num =  15  right_num =  0
raw: time:0.24s, speed:178.83st/s; acc: 0.9732, p: 0.0000, r: -1.0000, f: -1.0000
result (2)
build CRF...
Decode raw data, nbest: 1 ...
gold_num =  0  pred_num =  96  right_num =  0
raw: time:0.30s, speed:73.46st/s; acc: 0.8833, p: 0.0000, r: -1.0000, f: -1.0000
In result (1), the acc is high(acc:0.9732) and the NER predicted perfect such as PER which I want. However, in result (2), the acc(which is 0.8833) is not that good, and there are many PER predicted wrong. So if the acc value already shows that there is something wrong when predicting, why should it still gives the wrong decoding result. like  '王益' is the right PER in raw data, the model founds '王益作' as PER because there is '王益作出****' in the sentences.

**Comment by jiesutd** [comment]
The metrics are  meaningless when decoding raw data, as there is no gold standard to compare.

**Comment by Biaocsu** [comment]
as there is no gold standard, how do the acc comes out, I'm just confused about the value

**Comment by Biaocsu** [comment]
@jiesutd  as there is no gold standard, how do the acc comes out, I'm just confused about the value

**Comment by jiesutd** [comment]
Your input assumes there are some gold label, e.g. all input has the label of  O.  When decoding the raw text, you need to padding the raw text with a fake label. This is to keep it in the same format as ‘test’ model, so I don’t need to write new codes. Maybe I will refine the code in next version.

**Comment by Biaocsu** [comment]
I understood, thanks, really
