### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by HongyanJiao** [jiesutd/NCRFpp#117]
when encoding
crf.py", line 27, in log_sum_exp
    return max_score.view(-1, m_size) + torch.log(torch.sum(torch.exp(vec - max_score.expand_as(vec)), 1)).view(-1, m_size)  # B * M
RuntimeError: CUDA out of memory. Tried to allocate 158.25 MiB (GPU 0; 11.17 GiB total capacity; 10.56 GiB already allocated; 130.88 MiB free; 1.29 MiB cached)

**Comment by jiesutd** [comment]
It seems you do not have enough GPU memory for your task.
