### ISSUE TITLE
How to get mean nll loss only using crf ?

### ISSUE THREAD

**Issue by xyl576807077** [jiesutd/NCRFpp#123]
Hi, my research interest is computer vision. I want to use crf module in my work, Also I don't familiar with NLP. So I want to know how to get mean nll loss insteaf of sum nll loss

**Comment by jiesutd** [comment]
Please give more details about your question.

**Comment by xyl576807077** [comment]
Sorry.
My question is: In your crf module, It calculates the crf loss throw summing every sample score. For example
```
cur_values = self.transitions.view(1, tag_size, tag_size).expand(
batch_size, tag_size, tag_size) + partition.contiguous().view(batch_size, tag_size, 1).expand(batch_size, tag_size, tag_size)
cur_partition = log_sum_exp(cur_values, tag_size)
final_partition = cur_partition[:, STOP_TAG]
# It calcutates all sample score
return final_partition.sum(), scores
```
This caused my model loss over 100 million. Because I need to decode for every pixel of image using crf,  my data shape is [32 * 64 * 64, 5, 28].
So I want to know, how to get mean negtive log likelihood loss in crf ?

**Comment by xyl576807077** [comment]
您好，我还是用中文吧。看了之前的issue后，为了求平均的负对数似然，我把代码改成了一下形式，不知道对不对。在您最新的crf里面好像没有设置size_average这个参数
```
def neg_log_likelihood_loss(self, feats, mask, tags):
    # nonegative log likelihood
    batch_size = feats.size(0)
    forward_score, scores = self._calculate_PZ(feats, mask)
    gold_score = self._score_sentence(scores, mask, tags)
    return (forward_score - gold_score) / batch_size
```
在[Issue 68](https://github.com/jiesutd/NCRFpp/issues/68)提到了索引0是被占用了，当做了PAD的标志，那如果单独使用crf在我的项目里，我这边的索引0是有意义的，除了在参数初始化时删掉索引0的init之外，其他地方还需要修改吗？

**Comment by jiesutd** [comment]
the function `_calculate_PZ` is not the final loss of CRF, it is just part of it. The crf loss function is `neg_log_likelihood_loss `. `_calculate_PZ` can't be replaced with mean negative log likelihood, otherwise, it is not CRF.
