### ISSUE TITLE
File format error (utf-8 not read)

### ISSUE THREAD

**Issue by alimghl** [jiesutd/NCRFpp#125]
Hi, I am facing **an issue regarding to the file format**. I want to train NER MODEL by using this toolkit for URDU (an asian language) which is supported by **'UTF-8'** format. when I start to train (after changing in config file for my Dataset) it shows the following error.

> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5: character maps to '\<undefined\>'

after searching on internet for this problems most recommend solution is that
   set the encoding type to 'UTF-8' when reading a file.

please look into this issue and help me how to resolve this issue.

**Comment by alimghl** [comment]
![image](https://user-images.githubusercontent.com/52175795/60044293-78311e80-96db-11e9-89c4-16d0ece1f136.png)

**Comment by jiesutd** [comment]
Please refer https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character 

Just change the open file function at data.py file with `encoding="utf8"`. The file and line number is already shown in your screenshot.

**Comment by alimghl** [comment]
> 
> 
> Please refer https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character
> 
> Just change the open file function at data.py file with `encoding="utf8"`. The file and line number is already shown in your screenshot.

Yes It is working. Thanks a lot. 

**only small feedback Feedback.**
file data.py line 347
f = open(save_file, 'wb') 
 binary mode doesn't take an encoding argument
