### ISSUE TITLE
可以得到每个实体的Precision,Recall和F值吗？

### ISSUE THREAD

**Issue by FallingSlowly** [jiesutd/NCRFpp#127]
您好，我的数据集有B-SIGNS，I-SIGNS等五个实体，请问可以得到每个实体的Precision,Recall和F值吗？
非常感谢~

**Comment by jiesutd** [comment]
你好，我暂时没有实现这个部分，后续版本可能会写一个，不过暂时不支持。

**Comment by FallingSlowly** [comment]
@jiesutd 好的，谢谢~
