### ISSUE TITLE
Question about the F1 score in Section 2.

### ISSUE THREAD

**Issue by miracle24** [jiesutd/NCRFpp#13]
Hello. I want to know if the performance on CONLL 2003 English NER reported in Section 2 is the average performance or the maximum performance? Did you done the significant test? I think 91.20/91.26 is good, but the result of the significant test is needed for CONLL 2003 English NER.

**Comment by jiesutd** [comment]
Hi @miracle24 , Yes I totally agree with you!  Currently, the score of 91.20 and 91.26 is the result of a random seed.  

We have conducted the experiments under 5 different random seeds, the result is about 91.08+0.1 and 91.11+-0.2 . The statistical results will be systematically updated soon.

**Comment by miracle24** [comment]
Thanks a lot.
