### ISSUE TITLE
question about dset_dir

### ISSUE THREAD

**Issue by buptzcW** [jiesutd/NCRFpp#130]
hi @jiesutd thanks for your great NCRFpp, when i modified my train.config, i'm confused about what dset_dir exactly means in TRAIN. what will your NCRFpp use dset_dir do?

**Comment by jiesutd** [comment]
The current version saved the model in two files: dset_dir and model_dir. When you load the model, you need to load both files. 

My coming version will remove this config and keep the model saved in one file. I will update the NCRF++ soon.
