### ISSUE TITLE
TypeError: expected np.ndarray (got numpy.ndarray)

### ISSUE THREAD

**Issue by Biaocsu** [jiesutd/NCRFpp#131]
Hi, don't know whether for the version of pytorch, I use torch=1.10. and happend to this error, please help me, thanks.
File "E:\desktop\KG\NCRFpp\model\wordrep.py", line 45, in __init__
    self.word_embedding.weight.data.copy_(torch.from_numpy(data.pretrain_word_embedding))
TypeError: expected np.ndarray (got numpy.ndarray)

**Comment by Biaocsu** [comment]
there is something wrong with my code, and I solved it

**Comment by jiesutd** [comment]
Hi @Biaocsu , is the problem still exist?

**Comment by jiesutd** [comment]
Generally, it is the name of mismatch. When we import numpy, we normally use `import numpy as np`.

The information you provided is limited, I can't give you more suggestions without further information.

**Comment by Biaocsu** [comment]
Yes, the problem still exist. What’s more, using the same code, it happens to this error when running by windows, and when I run it by ubuntu then it is all right.  How can I help you to find the problem?

**Comment by jiesutd** [comment]
So the problem environment is Windows + PyTorch 1.0?  That's weird. Have you ever check the numpy version on Windows and Ubuntu?

**Comment by Biaocsu** [comment]
I will send you my code to see whether you can reappear the error, plus my environment is Windows + Pytorch 1.10 + Numpy 1.16.1
链接：https://pan.baidu.com/s/15b-NbsrDb5E7DqrjRjaslg 
提取码：ldw4

**Comment by jiesutd** [comment]
Have you changed the code?

**Comment by Biaocsu** [comment]
just a little bit, I think it will no matter

**Comment by jiesutd** [comment]
You can run my original code to see if it exists.

**Comment by Biaocsu** [comment]
yes! I just clone the code, and run it by Windows, the problem still exist, here is the complete output:
`E:\NCRFpp>python main.py --config demo.decode.config
Seed num: 42
MODEL: decode
sample_data/example.dev
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DATA SUMMARY START:
 I/O:
     Start   Sequence   Laebling   task...
     Tag          scheme: BMES
     Split         token:  |||
     MAX SENTENCE LENGTH: 250
     MAX   WORD   LENGTH: -1
     Number   normalized: True
     Word  alphabet size: 5104
     Char  alphabet size: 5104
     Label alphabet size: 14
     Word embedding  dir: data/embeddings/gigaword_chn.all.a2b.uni.ite50.vec
     Char embedding  dir: None
     Word embedding size: 50
     Char embedding size: 30
     Norm   word     emb: True
     Norm   char     emb: False
     Train  file directory: data/WPS/train.char.bmes
     Dev    file directory: data/WPS/dev.char.bmes
     Test   file directory: data/WPS/test.char.bmes
     Raw    file directory: sample_data/example.dev
     Dset   file directory: result/model/lstmcrf.dset
     Model  file directory: result/WPS/lstmcrf
     Loadmodel   directory: result/model/lstmcrf.72.model
     Decode file directory: sample_data/raw.out
     Train instance number: 81485
     Dev   instance number: 10040
     Test  instance number: 8973
     Raw   instance number: 0
     FEATURE num: 0
 ++++++++++++++++++++++++++++++++++++++++
 Model Network:
     Model        use_crf: True
     Model word extractor: LSTM
     Model       use_char: False
 ++++++++++++++++++++++++++++++++++++++++
 Training:
     Optimizer: sgd
     Iteration: 100
     BatchSize: 10
     Average  batch   loss: True
 ++++++++++++++++++++++++++++++++++++++++
 Hyperparameters:
     Hyper              lr: 0.015
     Hyper        lr_decay: 0.05
     Hyper         HP_clip: None
     Hyper        momentum: 0.0
     Hyper              l2: 1e-08
     Hyper      hidden_dim: 200
     Hyper         dropout: 0.5
     Hyper      lstm_layer: 1
     Hyper          bilstm: True
     Hyper             GPU: True
DATA SUMMARY END.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
nbest: 10
Load Model from file:  result/WPS/lstmcrf
build sequence labeling network...
use_char:  False
word feature extractor:  LSTM
use crf:  True
build word sequence feature extractor: LSTM...
build word representation...
Traceback (most recent call last):
  File "main.py", line 564, in <module>
    decode_results, pred_scores = load_model_decode(data, 'raw')
  File "main.py", line 480, in load_model_decode
    model = SeqLabel(data)
  File "E:\NCRFpp\model\seqlabel.py", line 31, in __init__
    self.word_hidden = WordSequence(data)
  File "E:\NCRFpp\model\wordsequence.py", line 25, in __init__
    self.wordrep = WordRep(data)
  File "E:\NCRFpp\model\wordrep.py", line 45, in __init__
    self.word_embedding.weight.data.copy_(torch.from_numpy(data.pretrain_word_embedding))
TypeError: expected np.ndarray (got numpy.ndarray)
`

**Comment by Biaocsu** [comment]
yes, I just clone the code and run it, the problem still exist. here is the output:
`Traceback (most recent call last):
  File "main.py", line 564, in <module>
    decode_results, pred_scores = load_model_decode(data, 'raw')
  File "main.py", line 480, in load_model_decode
    model = SeqLabel(data)
  File "E:\NCRFpp\model\seqlabel.py", line 31, in __init__
    self.word_hidden = WordSequence(data)
  File "E:\NCRFpp\model\wordsequence.py", line 25, in __init__
    self.wordrep = WordRep(data)
  File "E:\NCRFpp\model\wordrep.py", line 45, in __init__
    self.word_embedding.weight.data.copy_(torch.from_numpy(data.pretrain_word_embedding))
TypeError: expected np.ndarray (got numpy.ndarray)
`

**Comment by jiesutd** [comment]
Sorry, current I don't have available Windows environment to exam your problem. But I believe it is caused by some bugs in PyTorch rather than my code. 

You can find the same problem in other projects:

https://discuss.pytorch.org/t/why-do-i-get-typeerror-expected-np-ndarray-got-numpy-ndarray-when-i-use-torch-from-numpy-function/37525

Maybe I will find an environment to solve this problem, but I don't have time recently.

**Comment by Biaocsu** [comment]
yes, I see this. we will solve this, let's see

**Comment by XGuider** [comment]
https://discuss.pytorch.org/t/why-do-i-get-typeerror-expected-np-ndarray-got-numpy-ndarray-when-i-use-torch-from-numpy-function/37525
@jiesutd this is could help you  to solve.maybe you not change to torch.

**Comment by rilut** [comment]
It's also happening for me on numpy 1.17.4, my own solution is to downgrade to 1.16.4

**Comment by dionisole** [comment]
I have the same problem. Downgrading numpy to 1.16.4 did NOT help. Pytorch version: 1.4.0. 
Does anybody managed to find a proper solution?
