### ISSUE TITLE
断句功能，类似给句子标上逗号和句号。

### ISSUE THREAD

**Issue by shenxuhui** [jiesutd/NCRFpp#132]
作者你好，非常非常非常感谢你的工作。

最近想基于 NCRFpp 做一个断句的模型，具体来说就是： 来一个句子，判断这个句子是不是完整的句子。类似给句子标上逗号和句号。

尝试使用 Ncrfpp，实验参数及数据表示如下：

**参数配置：**
[train_config.txt](https://github.com/jiesutd/NCRFpp/files/3494993/train_config.txt)

**部分数据：**
[train_data.txt](https://github.com/jiesutd/NCRFpp/files/3495002/train_data.txt)

**数据说明：**
1. 数据中临时使用 S-LOC 作为断句标志，意思是这里是逗号或者句号。
2. 之前使用 crfpp 做过这个功能，当时的数据组织为：每句话都是完整的句子，然后把逗号，句号（句尾）标注成断句符号。训练之后发现不管是不是完整句子句尾都会被标注成 断句。
3. 当前的数据组织方式为，当前句子句尾加上下一句子的句首，大约 10 个字。训练后发现，完整的句子句尾会标注成不是断句，必须等待后续内容才能确定之前的句子是不是完整的句子。（这个是符合预期的）
4. 尝试训练数据一半是完整句子，一半是同一完整句子 + 下一句话的句首 10 个字，但是训练出来的性能非常差。

**我的问题是：**
如何组织训练数据才能真正达到断句的目的，也就是说来一个句子，判断是 完整句子 or 不是完整句子。

感谢！这个 issue 我持续提供实验结果，无论作者是否回复，已经非常感谢啦！

**Comment by jiesutd** [comment]
你好，不是特别清楚你的任务。我的初步理解是来了一个句子，如果里面没出现S-LOC, 那就是完整的句子，否则就不完整。
