### ISSUE TITLE
Can you help me ?

### ISSUE THREAD

**Issue by caoxu915683474** [jiesutd/NCRFpp#14]
Thanks for share this good work, can you help me?
I set the iteration to be 15000 times and find that the training process is too slow.And the F1 score always be 0.7 percent . So can you help me with the training problems? 

BTW, I find that your f1 depends on p and recall. But I found that others's work calculates it with acc and recall. May be I am wrong. So how can I get your score.And after how many epoch did you get the best score, so that I can set the iteration param.

I will appreciate for you help!

**Comment by jiesutd** [comment]
Hi @caoxu915683474 , which task do you want to train? NER? Generally set the iteration as 100 is enough, 15000 is way too much! If you trained your model on CoNLL 2003 English NER data, the F1=0.7 is too low, you need to check you input data. 

The calculation of F1-score is based on precision and recall. Different implementations may have different name, but the equation should be same. You can refer [https://en.wikipedia.org/wiki/F1_score](Here) for more information about F1-score.

**Comment by caoxu915683474** [comment]
Thanks for your quick answer , I just use the data that in your work. And thanks for the help with F1. So what I only do is clone your project and set the iteration as 15000 and run it without any change.

**Comment by jiesutd** [comment]
The provided data is a sample data. It does not contain the whole dataset in CoNLL03. You need to get the original full data and the embeddings to reproduce my result.

**Comment by udion** [comment]
I think get_ner_BIO() in metric.py is wrong.

consider the example where label_list = [I-MISC, I-MISC, O, I-PER, I-PER, O, O, O, O, O I-ORG, O] according to current function the following will happen :

Since there is no tag involving B-, whole_tag and tag_index will always be [] and hence the output of the function is [] which is wrong?

I am unable to find CoNLL-2003 in BIOMES format, is it available from official CoNLL website? If not can you provide reference to convert BIOMES to BIO?

**Comment by udion** [comment]
@jiesutd **yes, sorry foolish of me**
the above mentioned example is not even valid BIOES or BIO format so obviously `get_ner_BIO()` won't function the way it should be. forgive me for my noobness.

Thanks, I wrote a script to convert (what seems like IOB) to BIOES. I am a noob though and got to know about CoNLL few days back, I was wondering how you guys check if different versions (BIOES/BIO/IOB) data are correct, do you guys have an exhaustive set of tagged sequences on which you check your conversion scripts?

( P.S. please don't mind dumb questions )
