### ISSUE TITLE
about pos tag

### ISSUE THREAD

**Issue by mingroad** [jiesutd/NCRFpp#140]
hi, best wishes to you!
 i have a question about pos labeling. now you give a tag format(BIO, BMES,BIOES), but for ner,chunking etc on. so for pos, what is that? it seems no support. if it support, can you give a sample? data format samples? thanks.

**Comment by jiesutd** [comment]
You can just use the original pos tags. 

The only difference is to set `seg=False` in the config file. 

Details are here: https://github.com/jiesutd/NCRFpp/blob/master/readme/Configuration.md

**Comment by mingroad** [comment]
谢谢，在确认一疑问，关于结果评价实现metric.py，看到是针对BIO, BMES,BIOES的，关于pos这类原始标签类别，是否支持？看到您文章你有做这方面的结果，还是需要另实现？

**Comment by jiesutd** [comment]
不需要自己实现，会自动计算模型准确度accuracy的。
