### ISSUE TITLE
Find the viterbi score for each tag in output sequence

### ISSUE THREAD

**Issue by trannhuthuat96** [jiesutd/NCRFpp#143]
Hi @jiesutd,
Thanks for sharing your great sequence labeling implementation on PyTorch.

I'm using your code for my sequential tagging problem but struggling in finding viterbi score in function __viterbi_decode_ in module _crf.py_.

Particularly, when decoding optimal tag sequence using function __viterbi_decode_ in _crf.py_, I would like to not only return the optimal sequence but also the **viterbi score for each tag in the optimal output sequence**.

I attached my implementation below. Hope to receive your useful comments on my implementation.

Thanks and regards,

<img width="1182" alt="Screen Shot 2019-11-10 at 7 08 47 PM" src="https://user-images.githubusercontent.com/21955171/68543789-5c11ed80-03ee-11ea-849b-39882409cdff.png">

**Comment by jiesutd** [comment]
The Viterbi algorithm is to calculate a score for a specific **sequence** not to score each word.

**Comment by trannhuthuat96** [comment]
Hi @jiesutd ,
Thanks for your very quick response.

I agree with you that Viterbi algorithm is to calculate score for a specific sequence.

And the problem I'm facing is to trace back to find out how much score each word in optimal sequence is given when accumulating total score for the sequence (it's my implementation in line 130 and line 136).

Finally, does the first result (the underscore) in line 108 represent the final score for a sequence given by Viterbi algorithm?

Hope to receiver your response soon.

Thank you so much.
