### ISSUE TITLE
No pretrained embedding 

### ISSUE THREAD

**Issue by yeliu918** [jiesutd/NCRFpp#149]
there is no pretrained embedding, such as sample_data/lstmcrf in the config file

**Comment by jiesutd** [comment]
There is a sample pretrained embedding. https://github.com/jiesutd/NCRFpp/blob/master/sample_data/sample.word.emb

**Comment by yeliu918** [comment]
This is the word embedding, but not the pre-trained model weight. I'm asking the pre-trained model weight.

**Comment by jiesutd** [comment]
I didn't share it.
