### ISSUE TITLE
训练标点恢复时的问题（任务被kill，损失爆炸）

### ISSUE THREAD

**Issue by nastyZhao** [jiesutd/NCRFpp#150]
您好，我希望能利用该工具包训练中文标点恢复任务，在查阅说明以及issues区后进行了如下准备
数据的格式如下，有四个标点的标签（S-COMMA，S-PERIOD，S-QUESTIONMARK，S-QUESTIONMARK）EXCLAMATIONMARK）:

```
是 O
否 O
会 O
有 O
传 O
闻 O
中 O
的 O
高 O
低 O
两 O
个 O
版 O
本 O
呢 S-QUESTIONMARK

该 O
机 O
售 O
价 O
为 O
NUM O
美 O
元 S-COMMA
约 O
合 O
NUM O
元 O
人 O
民 O
币 S-PERIOD
```

在使用项目的默认配置（gpu=True）训练时，训练数据在8千万句（12Gb），运行任务一段时间后显示被kill掉。
我将训练数据降至1000万句（2Gb），任务运行成功，但最终结果显示为loss 爆炸

查看issues后我修改了config文件，
主要是改变的地方是将CNN换成了LSTM，
```
char_seq_feature=LSTM
#cnn_layer=4
```
但是运行系统显示1000万句的任务还是被kill掉。

之后我按照#107修改了config，同时设置seg=False，
仍然出现任务被kill的情况。

请问这主要是什么问题呢？数据的标注格式存在什么问题么？训练中文标点想利用字符（char）作为输入的时候还有什么需要注意的么？

**Comment by jiesutd** [comment]
格式看着没有什么问题。 但是你的输入已经是character based 的了，就没必要用char_seq_feature了，可以把use_char=False

**Comment by jiesutd** [comment]
loss 爆炸的话，你可能需要调整hyperparameters, 以及尝试不同的pretrain embeddings, 以及尝试是否需要norm_word_emb
