### ISSUE TITLE
About the oracle n-best score？

### ISSUE THREAD

**Issue by xiao2mo** [jiesutd/NCRFpp#151]
Hi, could u help me find out the definition of oracle score? I just can't find the related meaning of it . Many thanks.

**Comment by jiesutd** [comment]
The nbest decoding is normally used in reranking models to provide more available candidates. And the rerank system will learn how to choose the best sequence from the n-best candidate. The oracle results I reported is based on an assumption that the rerank system works perfectly to choose the best sequence from the n-best outputs. It is a standard metric to show the upbound of the rerank system. You may search the papers of reranking system for more details, or you can check our rerank paper: http://www.acl-bg.org/proceedings/2017/RANLP%202017/pdf/RANLP101.pdf.

**Comment by xiao2mo** [comment]
Got it. Thank u. I will refer to the paper.
