### ISSUE TITLE
关于复现 COLING 2018 paper NER task 任务 WLSTM+CRF+CCNN模型时遇到的一些问题

### ISSUE THREAD

**Issue by hzs0828** [jiesutd/NCRFpp#154]
您好,我在复现NER任务 WLSTM+CRF+CCNN模型的时候,有两个问题想请教您
1.我发现您论文中的NER数据统计部分和CONLL 2003数据集在dev和test句子数量上结果不一致,
论文统计结果:
![image](https://user-images.githubusercontent.com/52945343/89148852-89f71d80-d58d-11ea-9bfb-309e2951e130.png)
CONLL2003统计结果:
![2](https://user-images.githubusercontent.com/52945343/89149111-32a57d00-d58e-11ea-9bb1-2bb63b4d814c.png)
想请问您的论文中的数据集是怎么构建的呢

2.我使用CONLL 2003 NER数据集,复现WLSTM+CRF+CCNN模型结果时,未能达到您论文中的F1:91.35结果,我的最好的结果是F1:91.02(epochs: 97),数据已经转换为BIOES格式,对于demo.train.config只修改了word_emb_dim=100和Iteration=100,其他参数未改动,附上log信息和数据格式
log:
[WLSTM_crf_CCNN_BIOES_20200803_test.txt](https://github.com/jiesutd/NCRFpp/files/5014360/WLSTM_crf_CCNN_BIOES_20200803_test.txt)
数据格式:
[dev.txt](https://github.com/jiesutd/NCRFpp/files/5014364/dev.txt)
想请问您,我的复现结果达不到91.35是否跟数据量不一致有关呢,还是由于其他什么原因引起的呢

如有打扰到您,还请谅解,谢谢你!

**Comment by jiesutd** [comment]
你好，我确认了下数据分布，我用的conll  数据是3466 和3684 句，论文里应该是typo 了 。

91.35 应该是在有限几次尝试中最高值，平均值应该91.1 -91.2附近。你可以换几个random seed 试试。 

此外你得要修改pretraining embedding的目录，替换成你的pretrained embedding, demo 中只是给了个很小的embeddings， 不是完整的。
