### ISSUE TITLE
Some problems with the dataset.

### ISSUE THREAD

**Issue by caoxu915683474** [jiesutd/NCRFpp#16]
Excuse me, I can't find the conll data with BIOES tags.Where can I get the data to perform your score?
The score of BIO tags is something worse than BIOES ' s.

Can you give me a url to download the data?

thanks a lot for your help.

**Comment by zhenlanghuo** [comment]
@caoxu915683474 you need transform the BIO tags to BIOES tags by yourself.

**Comment by caoxu915683474** [comment]
@zhenlanghuo Thanks a lot , I forget to do this transform work by myself. Haha!

**Comment by jiesutd** [comment]
Thanks @zhenlanghuo !

**Comment by udion** [comment]
@caoxu915683474 were you able to resolve the issue? were you able to get BIOES dataset?
