### ISSUE TITLE
metric on "span"  level instead of  on token level of iob 

### ISSUE THREAD

**Issue by myeghaneh** [jiesutd/NCRFpp#160]
hi, how can we have a metric on span level? is there any way to use that?  (my labels are Claim and Premise)

I mean, I have a result on iob tokens like 

```
'B-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'I-P', 'O', 'O', 'O', 'O', 'O', 'B-C', 'I-C', 'I-C', 'I-C', 'I-C', 'I-C', 'I-C', 'I-C', 'I-C', 'I-C', 'O'`
```

how can I find the result on the Claim and Premise span?

**Comment by jiesutd** [comment]
Set `seg=True` in the configuration file. 

https://github.com/jiesutd/NCRFpp/blob/master/readme/Configuration.md
