### ISSUE TITLE
NER paper

### ISSUE THREAD

**Issue by lijiayi980130** [jiesutd/NCRFpp#162]
![Screenshot_20201224_133429_com tencent mtt](https://user-images.githubusercontent.com/31726855/103063966-62bede00-4578-11eb-8e8e-4d302cb3904f.jpg)
but it improve F1 in your paper

**Comment by jiesutd** [comment]
You need to understand what is the "Oracle scores" https://github.com/jiesutd/NCRFpp/issues/151#issuecomment-613114038. Please add your reply to the original issue https://github.com/jiesutd/NCRFpp/issues/161  rather than open a new issue.
