### ISSUE TITLE
Conll 使用内存大

### ISSUE THREAD

**Issue by wizare** [jiesutd/NCRFpp#164]
你好。我目前使用你的框架来做NER的实验，用的数据集conll2013。但在实验过程中我发现程序的内存占用很高，能高达40G，而且CPU占用也很高，几乎把机器的核数都占完了。

因为实验需要固定住预训练的embedding，所以对model/wordrep.py的48行进行了修改，但这应该影响不大。

**Comment by tonytonyjoba** [comment]
老哥   你的pytorch用的啥版本    我用python3.6+pytorch1.7.1跑不转呢   报错了。。

**Comment by jiesutd** [comment]
不确定你的修改是哪里，你先确认一下你的句子之间是否有空行分割。实际上不可能需要这么多内存
