### ISSUE TITLE
nbest score

### ISSUE THREAD

**Issue by myeghaneh** [jiesutd/NCRFpp#165]
I have got nbst=6 result (below)
 my question is how can i interpret this result? 

is it actually the answer of the best 6 models to our testing data? 
 
 how can I have the same chart for a best score as you had in your GitHub? 
``
# 0.9998 0.0000 0.0000 0.0000 0.0000 0.0000
International O O O O O O
tourism O O O O O O
is O O O O O O
now O O O O O O
more O O O O O O
common O O O I-P O I-P
than O I-P I-P I-P O I-P
ever O I-P O I-P I-P O
before O O O O O O

# 0.9962 0.0015 0.0011 0.0004 0.0004 0.0003
The O O O O O O
last O O O O O O
50 O O O O O O
years O O O O O O
have O O O O O O
seen O O O O O O
a O O O O O O
significant O O O O O O
increase O O O O O O
in O O O O O O
the O O O O O O
number O O O O O O
of O O O O O O
tourist O O O O O O
traveling O O O O O O
worldwide O O O O O O
. O O O O O O`
```

**Comment by jiesutd** [comment]
nbest lists the top n predict sequence and their corresponding probabilities.
