### ISSUE TITLE
Provision for Custom Features?

### ISSUE THREAD

**Issue by sush-infrrd** [jiesutd/NCRFpp#166]
Hello, I see that you allow for adding POS and capitalization as features. I was wondering if this could be augmented with other features? For instance I plan on using wordshape (eg 123&* -> ddd*& ; heE-123 -> xxX-ddd) as an additional feature. Is there a way to do this with NCRF++? 

Thanks

**Comment by jiesutd** [comment]
Yes, you can custom any features you want.
