### ISSUE TITLE
Predicted output sample count not equals to input count

### ISSUE THREAD

**Issue by lujiaying** [jiesutd/NCRFpp#17]
I found the sample number of decode output is less than decode input.
Do you just skip the sentence with no tag predicted?
Can I have all predicted result?

```
build word sequence feature extractor: LSTM...
build word representation...
build CRF...
Decode raw data, nbest: 1 ...
gold_num =  48612  pred_num =  44576  right_num =  32770
raw: time:150.02s, speed:149.76st/s; acc: 0.9298, p: 0.7351, r: 0.6741, f: 0.7033
```
My input count is **1514142**, and output count is **1510350**.

**Comment by jiesutd** [comment]
There is a configuration item `MAX_SENTENCE_LENGTH`, the default number is 250. The sentences which are longer than this number will be removed.

**Comment by lujiaying** [comment]
Thanks. I think that's the very reason.
