### ISSUE TITLE
Different results on CPU versus GPU

### ISSUE THREAD

**Issue by jd-coderepos** [jiesutd/NCRFpp#173]
Greetings,

Is this expected behavior that the hyperparameters which obtain good results on the CPU will not transfer to experiments run on GPU? At the moment, we obtain a sufficiently strong sequence labeler with default lr (0.015) and in 10 iterations. However, we see very low results using the same parameters when training on a GPU. Maybe this is expected and normal, I am just not aware...

Thank you for any help with clarification.

**Comment by jiesutd** [comment]
We do notice slight differences in CPU and GPU, but the difference is minor. 

Please refer to our paper for details:
https://www.aclweb.org/anthology/C18-1327.pdf
