### ISSUE TITLE
About MAX_SENTENCE_LENGTH parameter

### ISSUE THREAD

**Issue by jd-coderepos** [jiesutd/NCRFpp#178]
I see in `utils/data.py` the `MAX_SENTENCE_LENGTH` parameter is fixed as a constant at 250 words. In my training and test data, I have maybe two or three instances that exceed 250 words to about 300 or so. I was just curious if there is a technical reason that the parameter is a constant? Thank you very much.

**Comment by jiesutd** [comment]
You can update it manually. This is only an empirical number. You can change it based on your own data.

**Comment by jd-coderepos** [comment]
Thanks!
