### ISSUE TITLE
句子长度超过256后发生的奇妙bug

### ISSUE THREAD

**Issue by lujiaying** [jiesutd/NCRFpp#18]
```
# model/crf.py
#  def _viterbi_decode(self, feats, mask):
length_mask = torch.sum(mask, dim = 1).view(batch_size,1).long()
```

```
mask == [1, 1, ...,1]  # szie: 1 * 256
torch.sum(mask, dim=1)   # 当mask是ByteTensor时，结果是0
```

血崩 这个bug拖了我3天

**Comment by jiesutd** [comment]
Yes, this is a strange bug at PyTorch. I think I have reported this bug at https://discuss.pytorch.org/, but when I just check I found I didn't. : ) 

Thanks for your updates, will fix it soon.

**Comment by jiesutd** [comment]
Fixed, thanks again.

**Comment by lujiaying** [comment]
Have a nice dream
