### ISSUE TITLE
f score is -1

### ISSUE THREAD

**Issue by udion** [jiesutd/NCRFpp#22]
In the file `demo.train.config` I changed the iterations to 100 and batch_size to 32, dev and test scores are almost always -1. (Note this is on the sample_dataset that you have provided with the embeddings that you have provided)

**Comment by udion** [comment]
So I have CoNLL-2003 dataset, which I have modified to be in the following format to be consistent with format you provided in the sample_dataset 
```
EU I-ORG
rejects O
German I-MISC
call O
to O
boycott O
British I-MISC
lamb O
. O

Peter I-PER
Blackburn I-PER

(and more)
```
Now here is a screen shot of training after few iterations with the following configuration
```
batch_size = 10
embd : GloVe6B 100 dimensional

(other things same as your sample train config)
```
f1 score of dev and test set is consistently -1 throughout the training although the accuracy of train/dev/test keeps on improving. What exactly is the accuracy? how can increase in accuracy not help improve f1 score? Any clues?

How can

**Comment by udion** [comment]
Oh I understand that this is because it's using `label_type="BMES"` but I want to use `label_type="BIO"` can this be specified through config file? if yes then how?

**Comment by jiesutd** [comment]
You use the wrong data format. Only BIO and  BMES(BIOES) tag scheme are supported. You need to change your input data format rather than the tagScheme. The tagScheme is setted based on the input data format.
