### ISSUE TITLE
problem in config reader

### ISSUE THREAD

**Issue by udion** [jiesutd/NCRFpp#24]
why is tagScheme is initalised with `noSeg`?

 and it is not getting updated upon reading the config file, so far in my experiments tagscheme always defaults to `BIO` and not `BMES` how do you set the tagScheme? through config file (I don't think you've even written code for that)

**Comment by jiesutd** [comment]
noSeg is just an initial value, it represents the input format does not have the BIO/BMES format (such as POS tagging). The self.tagScheme will be updated automatically after loading the input file.
