### ISSUE TITLE
Design of character level feature extractor

### ISSUE THREAD

**Issue by udion** [jiesutd/NCRFpp#25]
Hi,
In the cnn feature extractor, is it the case that in a batch you are assuming all the words to be of the same length? If so, then there must have been padding to the smaller words, will it not disturb the char level features?

**Comment by jiesutd** [comment]
Yes, the batch implementation is used, so the character sequences are padded as the same length. There is a pooling operation following the CNN calculation, so the padding part will not affect the representation of character sequence.
