### ISSUE TITLE
What is decoding status？

### ISSUE THREAD

**Issue by hit-joseph** [jiesutd/NCRFpp#26]

**Comment by hit-joseph** [comment]
Hi
I have some question about the decoding status? what does it mean , Can you explain it more carefully, THANK YOU!

**Comment by jiesutd** [comment]
I can't explain "carefully" to you because you didn't ask the "careful" question.

**Comment by hit-joseph** [comment]
sorry，may be some net problem , my supplement can't be seen.
IN your demo.decode.config file ,raw_dir is the same as  dev set, may be  I don't really understand what the role of decode part? if the input is the dev data . what is the output can you give an sample fo raw.out file ?
thank you !

**Comment by hit-joseph** [comment]
抱歉，关于第二个问题，我还是用中文提下问，可能描述的更准确一些，decode的过程是指的是从输入数据到标注好这个序列的过程吗（以序列标注任务为例），就是就像decode test那部分一样，生成了一个标注序列，只是没有evaluate步骤

**Comment by jiesutd** [comment]
是的，不过应该也有evaluate步骤
