### ISSUE TITLE
Design of CNN word feature extractor

### ISSUE THREAD

**Issue by udion** [jiesutd/NCRFpp#27]
It seems like for the CNN word feature extractor, you are simply applying 1D convolution to each word embedding directly, it doesn't look at the neighboring words (which I think will be useful). Please correct me if I am wrong.

Can you point to the reference for the CNN method? I found this seminal work http://www.jmlr.org/papers/volume12/collobert11a/collobert11a.pdf

should it not consider the neighboring words (something like the diagram shown)?
![image](https://user-images.githubusercontent.com/18963158/41264226-830e3d4e-6e26-11e8-9aa2-94d60171e846.png)

**Comment by jiesutd** [comment]
CNN definite uses the neighboring words information. Otherwise, it is just a simple feedforward network.

You can learn how does nn.Conv1d work in PyTorch  here https://pytorch.org/docs/stable/nn.html#torch.nn.Conv1d

**Comment by udion** [comment]
@jiesutd 
In the `forward` for CNN (in the file wordsequence.py), we have the following ...

```
if self.word_feature_extractor == "CNN":
            word_in = F.tanh(self.word2cnn(word_represent)).transpose(2,1).contiguous()
            for idx in range(self.cnn_layer):
                if idx == 0:
                    cnn_feature = F.relu(self.cnn_list[idx](word_in))
                else:
                    cnn_feature = F.relu(self.cnn_list[idx](cnn_feature))
                cnn_feature = self.cnn_drop_list[idx](cnn_feature)
                cnn_feature = self.cnn_batchnorm_list[idx](cnn_feature)
feature_out = cnn_feature.transpose(2,1).contiguous()
``` 
**`wordrep`** returns `Variable(batch_size, sent_len, hidden_dim)`
passing it to the `word2cnn` and taking transpose of it gives us `Variable(batch_size,  hidden_dim, sent_len)`, If we apply 1D convolutions to this, it will convolve on the `hidden_dim (i.e the embedding dimensions)` and will not contain information about the neighbors which is captured in sent_len dimension, am I missing something?

**Comment by jiesutd** [comment]
No, it will include the neighbor's information. Just check the link I replied to you, especially notice the parameter kernal_size.
