### ISSUE TITLE
word embeddings

### ISSUE THREAD

**Issue by udion** [jiesutd/NCRFpp#28]
which word embeddings did you use to get the results as displayed?

**Comment by jiesutd** [comment]
Glove 100

**Comment by udion** [comment]
@jiesutd 

By default (like your sample config file). It won't use the additional features present in the training data (I want to ignore extra information, I just want to use BIOES tags, I have features like Caps and stuff like that, It won't be considered by default, right?)

**Comment by jiesutd** [comment]
If you do not need the extra features (e.g. Caps), you need to remove that information from the input data. Otherwise, the features will be calculated (if you don't config the features in the config file, default parameters are applied automatically).
