### ISSUE TITLE
Python 3+

### ISSUE THREAD

**Issue by nishkalavallabhi** [jiesutd/NCRFpp#29]
By any chance, do you know if this is compatible with Python3+? I noticed you mentioned 2.7 in your requirements.

**Comment by jiesutd** [comment]
I am afraid not. I haven't tested it under Python 3. 

You can try it, but you at least you need manually convert the `print "abc"` as `print("abc")`

**Comment by jiesutd** [comment]
Hi @nishkalavallabhi thanks to @cclauss , NCRF++ currently support the Python 3, at least in a compatible syntax. You may have a try if you are interest.

**Comment by nishkalavallabhi** [comment]
Thanks!
