### ISSUE TITLE
Bug in IOBES converter?

### ISSUE THREAD

**Issue by dpressel** [jiesutd/NCRFpp#36]
It appears from your sample that there may be a bug in your IOBES converter, which Im assuming will affect your paper findings slightly?

An example would be at line 6845 of `train.bmes.txt`:
```
English S-MISC
County S-MISC
Championship S-MISC
cricket O
matches O
on O
Thursday O
: O
```
The original file in IOB1 has this:

```
English NNP I-NP I-MISC
County NNP I-NP B-MISC
Championship NNP I-NP I-MISC
cricket NN I-NP O
matches NNS I-NP O
on IN I-PP O
Thursday NNP I-NP O
: : O O
```

**Comment by jiesutd** [comment]
Hi @dpressel , thank you very much for your notification!

Yes, you are right! I didn't realize this problem before as I got the BIO format from my friend directly. After double check the original IOB data, there does exist the small bug you raised. 

To investigate the effectiveness of the tag conversion, I have written a [tagSchemeConvertor.py](https://github.com/jiesutd/NCRFpp/blob/master/utils/tagSchemeConvertor.py) and checked the original train/dev/test data. I found the number of inconsistent labels on train/dev/test are 24/1/7, which are too little to affect the final results in my experiments.  And I just rerun the experiments on the updated data and the results confirm that this small bug does not affect the final results.

Anyway, thanks again for your notification.
