### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by fgaim** [jiesutd/NCRFpp#38]
Thanks for the nice work. A minor issue, you have implemented support for Python 3 by catching the `ModuleNotFoundError` exception, which is fine for Python version 3.6 but will cause an error in versions <=`3.5`.

A quick solution would be to use `ImportError` instead of `ModuleNotFoundError`, at lines 24 and 14 in `main.py` and `utils/data.py`, respectively.

**Comment by jiesutd** [comment]
Fixed, thank you very much! @fgaim
