### ISSUE TITLE
Config files for best reported CoNLL results

### ISSUE THREAD

**Issue by yiyangnlp** [jiesutd/NCRFpp#41]
Hi,

Can you provide your config files for the reported CoNLL numbers (under section 3. Performance)?

Thanks,
Yi

**Comment by jiesutd** [comment]
The hyperparameters are listed in [ this paper](https://arxiv.org/pdf/1806.04470.pdf). Generally, the final results are various in different computer or environment, you can change the seed number to get different results.

**Comment by dhwajraj** [comment]
results are not reproducible by using params written in paper. Can you better provide config file for your results.

**Comment by jiesutd** [comment]
@dhwajraj please give me your log file in your experiments. I will help you checking if you use the wrong setting or data format.
