### ISSUE TITLE
Print statement doesn't automatically flush stdout/stderr on python 3

### ISSUE THREAD

**Issue by qiuwei** [jiesutd/NCRFpp#51]
As the title states, the behavior is different on python2. 
A better option is to use a standard logging module.

**Comment by jiesutd** [comment]
Hi @qiuwei  thanks for the suggestion. 

Can you give a more detail description about the flush operator? As I already used several `sys.stdout.flush()` to force the system print the logs.

**Comment by qiuwei** [comment]
If I use ncrfpp with python3, the log is not written to the stdout immediately as with python 2.
That's default behavior at the moment if don't make any modifications to the code at the moment.

With the sample data, it's hard to notice though. On my own dataset, I noticed the log was flushed only after every 20ish epochs.

**Comment by nthoangcute** [comment]
Epoch: 0/1
 Learning rate is set as: 0.015
Traceback (most recent call last):
  File "main.py", line 438, in <module>
    train(data)
  File "main.py", line 328, in train
    batch_word, batch_features, batch_wordlen, batch_wordrecover, batch_char, batch_charlen, batch_charrecover, batch_label, mask  = batchify_with_label(instance, data.HP_gpu)
  File "main.py", line 236, in batchify_with_label
    mask[idx, :seqlen] = torch.Tensor([1]*seqlen)
TypeError: mul() received an invalid combination of arguments - got (list), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (list)
 * (Number other)
      didn't match because some of the arguments have invalid types: (list)

**Comment by nthoangcute** [comment]
@jiesutd opss! My pytorch is currently 0.5.0a0.
```
Traceback (most recent call last):
  File "main.py", line 440, in <module>
    train(data)
  File "main.py", line 284, in train
    model = SeqModel(data)
  File "/root/vietbt/NCRFpp/model/seqmodel.py", line 31, in __init__
    self.word_hidden = WordSequence(data)
  File "/root/vietbt/NCRFpp/model/wordsequence.py", line 71, in __init__
    self.lstm = self.lstm.cuda()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 112, in _apply
    self.flatten_parameters()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 105, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```
Maybe I have to downgrade my pytorch version to 0.3

**Comment by siyecaoh** [comment]
我现在用的Python是2.7，pytorch是0.3，但是还是报错：Traceback (most recent call last):
  File "main.py", line 438, in <module>
    train(data)
  File "main.py", line 328, in train
    batch_word, batch_features, batch_wordlen, batch_wordrecover, batch_char, batch_charlen, batch_charrecover, batch_label, mask  = batchify_with_label(instance, data.HP_gpu)
  File "main.py", line 236, in batchify_with_label
    mask[idx, :seqlen] = torch.Tensor([1]*seqlen)
TypeError: mul() received an invalid combination of arguments - got (list), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (list)
 * (Number other)
      didn't match because some of the arguments have invalid types: (list)
