### ISSUE TITLE
Documentation for main_parse

### ISSUE THREAD

**Issue by twhughes** [jiesutd/NCRFpp#55]
I'm trying to get a pre-trained model to run via the command line using main_parse but am having issues.  

It would be helpful to have some documentation on the command line arguments for this function.

Thanks

**Comment by twhughes** [comment]
Ok thanks I'll check it out.  Just wasn't sure if one existed already.  Instead of a full documentation, do you have just a simple example of it in action?

**Comment by jiesutd** [comment]
You can try
 `python main_parse.py --wordemb %dir_pretrain_emb --status train --train %dir_train_file --dev %dir_dev_file ............`
detail arguments are shown in https://github.com/jiesutd/NCRFpp/blob/dac0432681291a8149a28d18451f64d0b4414776/main_parse.py#L416
