### ISSUE TITLE
total_batch = train_num//batch_size+1

### ISSUE THREAD

**Issue by Robert201806** [jiesutd/NCRFpp#56]
https://github.com/jiesutd/NCRFpp/blob/d560e276a5d7f1a29ae21f7dc7330bd71642aaf9/main.py#L319
 I think it should be 'total_batch = (train_num-1)//batch_size+1'.

**Comment by jiesutd** [comment]
Yes, it seems you are right, although the previous version is also reasonable as I add the line https://github.com/jiesutd/NCRFpp/blob/d560e276a5d7f1a29ae21f7dc7330bd71642aaf9/main.py#L323

Your implementation is more elegant.
