### ISSUE TITLE
Problem of using glove 100 on Windows

### ISSUE THREAD

**Issue by mading0817** [jiesutd/NCRFpp#57]
If you using glove 100 on Windows, it will probably have some errors about gbk encoding.
So the solution is changing the code in functions.py, line 128:
`with open(embedding_path, 'r') `as file:
add encoding = "utf-8" like the following:
`with open(embedding_path, 'r',encoding="utf-8") as file:`

**Comment by softhuafei** [comment]
hi，您好，请问您是在哪里下载的glove100预训练词向量呢？我看到https://github.com/stanfordnlp/GloVe上只有300dim的预训练词向量？
