### ISSUE TITLE
Probability of an Output Sequence

### ISSUE THREAD

**Issue by Rigeru** [jiesutd/NCRFpp#59]
Hi,
I want to get probability of each output sequence ( not n-best score ) when decoding.
How to get this? 
(How to get partition function Z when decoding?)

**Comment by jiesutd** [comment]
Hi, you can use the nbest decoding, the probability of each output sequence will be given. Notice the sequence probability of nbest decoding is normalized within the n decided sequence (I.e. the sum of the probabilities on n decoded sequence is 1.)

**Comment by marctorrellas** [comment]
Hi @jiesutd (and  👏 for the amazing library). In the docstring of both `_viterbi_decode_nbest` and `_viterbi_decode` it says `not implemented` for `path_score`. However, it looks to me that it is implemented indeed (and even more according to your comment above). Is that an oudated docstring?

`def _viterbi_decode_nbest(self, feats, mask, nbest):
        """
            input:
                feats: (batch, seq_len, self.tag_size+2)
                mask: (batch, seq_len)
            output:
                decode_idx: (batch, nbest, seq_len) decoded sequence
                path_score: (batch, nbest) corresponding score for each sequence (to be implementated)
                nbest decode for sentence with one token is not well supported, to be optimized`
