### ISSUE TITLE
issue with data initialization

### ISSUE THREAD

**Issue by PhantomGrapes** [jiesutd/NCRFpp#62]
Sorry for this repeative post, I'd just clicked submit accidently before I finished writting description. 

As we can see in the _main.py_
```python
def data_initialization(data):
    data.initial_feature_alphabets()
    data.build_alphabet(data.train_dir)
    data.build_alphabet(data.dev_dir)
    data.build_alphabet(data.test_dir)
    data.fix_alphabet()
```
words in the test and dev file are used to build **data.word_alphabet**  in _data.py_

```python
def build_alphabet(self, input_file):
        in_lines = open(input_file,'r').readlines()
        for line in in_lines:
            if len(line) > 2:
                pairs = line.strip().split()
                word = pairs[0]
                if self.number_normalized:
                    word = normalize_word(word)
                label = pairs[-1]
                self.label_alphabet.add(label)
                self.word_alphabet.add(word)
```
So that the oov problem is hidden as a result of this operation. 
If we comment _data.build_alphabet(data.dev_dir)_ and _data.build_alphabet(data.test_dir)_ in _main.py_, the f1 score will decrease by about 5% in test data.
So is this just a mistake or there are some other considerations concerning this operation? 
Thanks

**Comment by jiesutd** [comment]
Actually, the oov problem you raised is the out of embeddings (OOE) problem. By adding the dev/test words into alphabet will not affect the final result, but it can make some OOV words have a good pretrained embeddings. But we can also get the same results if we keep all the pretrained Word embeddings in the word alphabet. So this is only a fast implementation which saves the memory usage but does not change the system performance in real application.
