### ISSUE TITLE
How can I add custom numerical features?

### ISSUE THREAD

**Issue by amit2319** [jiesutd/NCRFpp#63]
I have some OCR dataset and want to include numerical features of the data such as their position in the document, but don't want an embedding of it.

**Comment by jiesutd** [comment]
Hi, it is actually a good feature request. But unfortunately, NCRF++ currently does not support this function. I have implemented the numerical features using another package (LibN3L) but didn't integrate the function here. 

Will consider adding this function in the future version, I don't have time to implement it recently as it's my graduation time.

**Comment by amit2319** [comment]
Thanks, I will dig into LibN3L and see what can I get.
Congratulations!

**Comment by amit2319** [comment]
Alright, I will see what can be done.
Hope to see the feature on this repo in the future though.

**Comment by carly95** [comment]
I am looking forward to this function too. Hope to see the implementation.

**Comment by bratao** [comment]
@jiesutd This feature would be awesome. +1 from me too!!
