### ISSUE TITLE
number of lstm layers for good performance

### ISSUE THREAD

**Issue by udion** [jiesutd/NCRFpp#64]
Hi @jiesutd 

For conll-2003 dataset, did you get optimal results for 1 layer lstm (if not, then how many did you stack to get optimal results?)

**Comment by jiesutd** [comment]
All the reported results are based on 1 layer LSTM.

**Comment by udion** [comment]
@jiesutd 

do you think stacking multiple layers would help? (what's your intuition about it?)

**Comment by jiesutd** [comment]
I remember someone has tried that, it seems multiple layers gives very limited improvement (not quite sure).
