### ISSUE TITLE
Parameter settings of NER model

### ISSUE THREAD

**Issue by lixin4ever** [jiesutd/NCRFpp#65]
Hi Jie,
         Thanks for making this awesome tool publicly available. Can you provide the parameter settings of the LSTM-CRF models you use to reproduce the results on CoNLL 03 NER dataset?
         Thanks in advance~

**Comment by jiesutd** [comment]
Hi  the `demo.train.config` includes the parameters I used in my paper. The only thing you need to change is to set `iteration=1` as `iteration=100`.
