### ISSUE TITLE
label probabilities

### ISSUE THREAD

**Issue by Rigeru** [jiesutd/NCRFpp#66]
Hi again,
I want to get **label probability** for each token like that,

> Rockwell        NNP     B       B/0.992465
> International   NNP     I       I/0.979089
> Corp.   NNP     I       I/0.954883
> 's      POS     B       B/0.986396
> Tulsa   NNP     I       I/0.991966

Is it possible?

**Comment by jiesutd** [comment]
Currently it is not supported for CRF layer. But for softmax layer, it is not hard to get the label probability with slightly code modification.
