### ISSUE TITLE
got -1 for precision and F1

### ISSUE THREAD

**Issue by cotitan** [jiesutd/NCRFpp#67]
gold_num =  992  pred_num =  0  right_num =  0
Dev: time: 2.86s, speed: 98.30st/s; acc: 0.8030, p: -1.0000, r: 0.0000, f: -1.0000
Exceed previous best f score: -10
Save current best model in file: sample_data/lstmcrf.0.model
gold_num =  930  pred_num =  0  right_num =  0
Test: time: 2.48s, speed: 103.37st/s; acc: 0.8011, p: -1.0000, r: 0.0000, f: -1.0000
why?

**Comment by jiesutd** [comment]
Please provide more information of your experiment (dataset, parameter etc. a log file would be better) if you still have the problem.

**Comment by cotitan** [comment]
Thanks. I was just too hasty. When it comes to the 2nd epoch, the precision is not -1 anymore. It is now a positive number. And I've closed that issue.


________________________________
