### ISSUE TITLE
Some questions about reproducing the results in  COLING 2018 paper,

### ISSUE THREAD

**Issue by HAWLYQ** [jiesutd/NCRFpp#74]
Hi, jie!  To reproduce the results of  `Char CNN + Word LSTM + CRF` model on CoNLL2003 NER task, I set the `iteration=1` as `iteration=100` in configuration file `demo.train.config` , put glove.6B.100d.txt  in directory "sample_data"  and revised I/O paths. Then I ran "python main.py --config demo.train.config".  After 100 epochs, the test F1-score was only 81.86, which was much lower than reported result 91.11. Could you give me some suggestions? (I didn't revise any hyper-parameters in your default configuration file "demo.train.config" as you mentioned in your "README.md")

**Comment by HAWLYQ** [comment]
Thanks for your reply. This is my training log file.
[ccnnlstmcrf_sent_conll.log](https://github.com/jiesutd/NCRFpp/files/2463702/ccnnlstmcrf_sent_conll.log)

**Comment by jiesutd** [comment]
@HAWLYQ Hi, I checked your log file. The parameter setting is OK. The strange thing is that in line 9 of your log `pretrain word:400000, prefect match:3, case_match:0, oov:1, oov%:0.2`. I believe you are using incorrect input data format. 

You can share a sample data of your input for checking.

**Comment by HAWLYQ** [comment]
@jiesutd I think i get it, I will change the input data format and have a try.  Thanks for your help.

**Comment by jiesutd** [comment]
@HAWLYQ You are welcome.
