### ISSUE TITLE
Computing of char BiLSTM

### ISSUE THREAD

**Issue by ZxYuan** [jiesutd/NCRFpp#75]
In NCRFpp/model/charbilstm.py
```
def get_last_hiddens(self, input, seq_lengths):
        """
            input:
                input: Variable(batch_size, word_length)
                seq_lengths: numpy array (batch_size,  1)
            output:
                Variable(batch_size, char_hidden_dim)
            Note it only accepts ordered (length) variable, length size is recorded in seq_lengths
        """
        batch_size = input.size(0)
        char_embeds = self.char_drop(self.char_embeddings(input))
        char_hidden = None
        pack_input = pack_padded_sequence(char_embeds, seq_lengths, True)
        char_rnn_out, char_hidden = self.char_lstm(pack_input, char_hidden)
        char_rnn_out, _ = pad_packed_sequence(char_rnn_out)
        return char_hidden[0].transpose(1,0).contiguous().view(batch_size,-1)
```
Is there any reason for ``char_hidden[0].transpose(1,0).contiguous().view(batch_size,-1)``?

I suppose we should concatenate ``char_hidden[0]`` and ``char_hidden[1]`` to form the feature of char BiLSTM

**Comment by jiesutd** [comment]
Hi @ZxYuan , the current version already includes the bidirectional output. In PyTorch 0.3, `char_hidden` is actually a tuple `(h_t, c_t)`. So here, `char_hidden[0]` is `(2, batch_size, lstm_dimension)`. After the transpose and view, the final output is the concatenation of final states in both directions.
