### ISSUE TITLE
Last sentence missing while decoding

### ISSUE THREAD

**Issue by Ji-Xin** [jiesutd/NCRFpp#83]
When I was doing decoding (sequence labeling), the last sentence from the input file is missing from the output file. This is not because of the MAX_SENT_LENGTH (I change that from 250 to 2500, but this problem is still there).

Then I tried to add a new blank line at the end of the input file, and then the problem is solved. It happens that none of the files inside sample_data ends with a blank line, and that's probably the reason. I guess the problem is in the `read_instance` function inside `function.py`, but haven't figured out where exactly it is yet.

**Comment by jiesutd** [comment]
Hi @Ji-Xin, thanks for your information. 

Yes, the previous version will not include the last sentence if your sentence does not follow with a blank line. It has been just fixed. You can download the updated code and have a try!

Thanks and welcome any of your feedback.
