### ISSUE TITLE
NameError: global name 'SeqModel' is not defined

### ISSUE THREAD

**Issue by ai-zhong** [jiesutd/NCRFpp#84]
Hi, thanks for the great project! 
So when I ran the demo.decode.config, it says 'SeqModel' is not defined.
it's in File "main.py", line 500, in load_model_decode, model = SeqModel(data);
Can you help with the issue?
Thanks a lot!

**Comment by jiesutd** [comment]
Hi @ai-zhong , thanks for this report! It is caused by a temporal bug when I am developing the next version. It has been fixed in the updated version. 

Please use the most recent code.

**Comment by ai-zhong** [comment]
Thanks for the quick response!
