### ISSUE TITLE
sentence classification

### ISSUE THREAD

**Issue by jonnykira** [jiesutd/NCRFpp#86]
Hello,

I noticed that there is an option `sentence_classification` that is not mentioned in the README.

Could you provide some details on how to use this option? Does this only use sentence level labels? and if so how should the training data look?

Thanks

**Comment by jiesutd** [comment]
@jonnykira Yes, I am working on integrating the sentence/document classification function into NCRF++. But it is still under development. Will release this features with a detail description in next version (within one month if everything goes smoothly).

**Comment by jiesutd** [comment]
Released in the dev version: https://github.com/jiesutd/NCRFpp/tree/dev
