### ISSUE TITLE
[feature request] entity level sentiment analysis

### ISSUE THREAD

**Issue by monajalal** [jiesutd/NCRFpp#9]
Is it possible that you add a entity level sentiment analysis wrapper to this?

**Comment by jiesutd** [comment]
Hi @monajalal , thanks for your interest. 

I am not quite sure about your feature requirement. 

Do you mean to recognize the entity and give the sentiment polarity for each recognized entity? In this case, you can simply change your data format which consists the polarity of entity (such as B-pos, I-pos or B-neg, I-neg).

If the entities are already given, then the basic approach is to merge the entity span as one word (you can add extra neural features to represent the entity) and do the sequence labeling. 

Anyway, the above suggestions just show this toolkit can solve the sentiment problems after a simple format conversion. This toolkit focuses on the sequence labeling problem, so I do not plan to add other feature which is not generic.

On the other hand, it should not be hard to fit this tool into the sentiment analysis problem if you want to change the source code.
