### ISSUE TITLE
self.word2cnn = nn.Linear(self.input_size, data.HP_hidden_dim)

### ISSUE THREAD

**Issue by cswangjiawei** [jiesutd/NCRFpp#91]
When word_feature_extractor== "CNN", why add a full connection layer before the convolution layer?

**Comment by jiesutd** [comment]
Do you mean the layer of word2cnn ? It is used to map the size of word representation vectors into the size of CNN hidden units. 

https://github.com/jiesutd/NCRFpp/blob/ac3497c931bab27806c19dffb382d86f2500c9a2/model/wordsequence.py#L48

**Comment by cswangjiawei** [comment]
Thank you very much! Why mapping the size of word representation vectors into the size of CNN hidden units?Can `it(self.word2cnn = nn.Linear(self.input_size, data.HP_hidden_dim))` be deleted and modify`self.cnn_list.append(nn.Conv1d(data.HP_hidden_dim, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`to`self.cnn_list.append(nn.Conv1d(self.input_size, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`?

**Comment by cswangjiawei** [comment]
Thank you very much! Why mapping the size of word representation vectors into the size of CNN hidden units?Can `it(self.word2cnn = nn.Linear(self.input_size, data.HP_hidden_dim))` be deleted and modify`self.cnn_list.append(nn.Conv1d(data.HP_hidden_dim, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`to`self.cnn_list.append(nn.Conv1d(self.input_size, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`?

**Comment by jiesutd** [comment]
> Thank you very much! Why mapping the size of word representation vectors into the size of CNN hidden units?Can `it(self.word2cnn = nn.Linear(self.input_size, data.HP_hidden_dim))` be deleted and modify`self.cnn_list.append(nn.Conv1d(data.HP_hidden_dim, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`to`self.cnn_list.append(nn.Conv1d(self.input_size, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`?

Of course you can, the reason I wrote in this way is that this is a "lazy implementation" (just to keep the `append` action within the same loop). And I think it's worthy to try your implementation.
