### ISSUE TITLE
F1测试

### ISSUE THREAD

**Issue by chuanfanyoudong** [jiesutd/NCRFpp#92]
您好；

十分荣幸看到您的github，我在跑您代码的时候看到您的utils/metric.py中30行是不是要改成“if label_type == "BMES" or label_type == "BIOES":”这样？
![image](https://user-images.githubusercontent.com/26218339/52892434-583d9b80-31cd-11e9-92b4-5c0e5a036735.png)

**Comment by jiesutd** [comment]
Yes, you are right! Will update the code soon. 
Thank you very much!

**Comment by jiesutd** [comment]
Fixed, thanks!
