### ISSUE TITLE
self.word2cnn = nn.Linear(self.input_size, data.HP_hidden_dim)

### ISSUE THREAD

**Issue by cswangjiawei** [jiesutd/NCRFpp#94]
Why mapping the size of word representation vectors into the size of CNN hidden units?Can `self.word2cnn = nn.Linear(self.input_size, data.HP_hidden_dim)` be deleted and modify`self.cnn_list.append(nn.Conv1d(data.HP_hidden_dim, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`to`self.cnn_list.append(nn.Conv1d(self.input_size, data.HP_hidden_dim, kernel_size=kernel, padding=pad_size))`?

**Comment by jiesutd** [comment]
Of course you can, the reason I wrote in this way is that this is a "lazy implementation" (just to keep the `append` action within the same loop). And I think it's worthy to try your implementation.

#91
