### ISSUE TITLE
alphabet.py中default index的使用 

### ISSUE THREAD

**Issue by softhuafei** [jiesutd/NCRFpp#95]
您好，我发现您在alphabet.py中，将default index=0也当做了词表的一个元素，并计入词表的大小。这样做会导致模型的预测label中包含label 0，而在获取标签0对应的真实标签时，您是返回了词表中的第一个真实标签，请问这么做是否会影响到模型的准确性？即模型的分类结果会增加一个默认标签，且您将该默认标签等同于数据中的第一种真实标签。

**Comment by jiesutd** [comment]
你好，一般情况下只要有少量训练数据，且模型能正常训练，则不会有影响。因为训练预料并没有label=0, 模型经过正常训练后几乎不可能预测出label=0. 极少数情况下将其重置成第一个label也几乎不影响结果。

**Comment by softhuafei** [comment]
懂了，感谢您的解答：）
