### ISSUE TITLE
Shuffling train ids

### ISSUE THREAD

**Issue by jonnykira** [jiesutd/NCRFpp#98]
I am a bit confused about the line:
https://github.com/jiesutd/NCRFpp/blob/ab82b6868bb81bedbac3e231d8e09f7341321e6f/main.py#L393   

Doesn't shuffling the data throw away useful information about the sequence? For example, the data in `sample_data` consists of sequences of sentences which are delimited by document delimiter tokens (`-DOCSTART-`). If the sentences are shuffled the model cannot learn from sequential relationships between sentences. 

I would imagine that for sentence classification tasks, shuffling in this way is probably worse still?

**Comment by jiesutd** [comment]
This is a good question. 
The model only takes a single sentence into consideration. It will not use the information between sentences. So this shuffle does not affect the model.

**Comment by jonnykira** [comment]
I see. Thanks for you quick reply!

**Comment by jonnykira** [comment]
It would be interesting to see if batching whole documents together and preserving the sequential nature of the data would affect performance.

**Comment by jiesutd** [comment]
That would be much slower than the single sentence. There has a previous work to include the whole document in CNN framework and shows slight improvement. https://arxiv.org/pdf/1702.02098.pdf

**Comment by jonnykira** [comment]
Interesting, thanks for the reference.

**Comment by cpmss521** [comment]
I'm confused about this question，sepecially in the sequence labeling task ，can you give me more hint?
